// Code generated by ent, DO NOT EDIT.

package rule

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the rule type in the database.
	Label = "rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldConnectionID holds the string denoting the connection_id field in the database.
	FieldConnectionID = "connection_id"
	// FieldLibraryKey holds the string denoting the library_key field in the database.
	FieldLibraryKey = "library_key"
	// FieldGranularity holds the string denoting the granularity field in the database.
	FieldGranularity = "granularity"
	// EdgeConnection holds the string denoting the connection edge name in mutations.
	EdgeConnection = "connection"
	// Table holds the table name of the rule in the database.
	Table = "rules"
	// ConnectionTable is the table that holds the connection relation/edge.
	ConnectionTable = "rules"
	// ConnectionInverseTable is the table name for the Connection entity.
	// It exists in this package in order to avoid circular dependency with the "connection" package.
	ConnectionInverseTable = "connections"
	// ConnectionColumn is the table column denoting the connection relation/edge.
	ConnectionColumn = "connection_id"
)

// Columns holds all SQL columns for rule fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldEnabled,
	FieldAction,
	FieldConnectionID,
	FieldLibraryKey,
	FieldGranularity,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// LibraryKeyValidator is a validator for the "library_key" field. It is called by the builders before save.
	LibraryKeyValidator func(string) error
)

// Action defines the type for the "action" enum field.
type Action string

// ActionDoNothing is the default value of the Action enum.
const DefaultAction = ActionDoNothing

// Action values.
const (
	ActionChangeQualityAndSearch  Action = "change_quality_and_search"
	ActionDelete                  Action = "delete"
	ActionDoNothing               Action = "do_nothing"
	ActionUnmonitorAndDeleteFiles Action = "unmonitor_and_delete_files"
	ActionUnmonitorAndKeepFiles   Action = "unmonitor_and_keep_files"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionChangeQualityAndSearch, ActionDelete, ActionDoNothing, ActionUnmonitorAndDeleteFiles, ActionUnmonitorAndKeepFiles:
		return nil
	default:
		return fmt.Errorf("rule: invalid enum value for action field: %q", a)
	}
}

// Granularity defines the type for the "granularity" enum field.
type Granularity string

// Granularity values.
const (
	GranularitySeason  Granularity = "season"
	GranularityEpisode Granularity = "episode"
)

func (gr Granularity) String() string {
	return string(gr)
}

// GranularityValidator is a validator for the "granularity" field enum values. It is called by the builders before save.
func GranularityValidator(gr Granularity) error {
	switch gr {
	case GranularitySeason, GranularityEpisode:
		return nil
	default:
		return fmt.Errorf("rule: invalid enum value for granularity field: %q", gr)
	}
}

// OrderOption defines the ordering options for the Rule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByConnectionID orders the results by the connection_id field.
func ByConnectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectionID, opts...).ToFunc()
}

// ByLibraryKey orders the results by the library_key field.
func ByLibraryKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLibraryKey, opts...).ToFunc()
}

// ByGranularity orders the results by the granularity field.
func ByGranularity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGranularity, opts...).ToFunc()
}

// ByConnectionField orders the results by connection field.
func ByConnectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConnectionStep(), sql.OrderByField(field, opts...))
	}
}
func newConnectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConnectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
	)
}
