// Code generated by ent, DO NOT EDIT.

package rule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/oom-killed/lib-managerr/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Rule {
	return predicate.Rule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Rule {
	return predicate.Rule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Rule {
	return predicate.Rule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Rule {
	return predicate.Rule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Rule {
	return predicate.Rule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Rule {
	return predicate.Rule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Rule {
	return predicate.Rule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldName, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldEnabled, v))
}

// ConnectionID applies equality check predicate on the "connection_id" field. It's identical to ConnectionIDEQ.
func ConnectionID(v int) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldConnectionID, v))
}

// LibraryKey applies equality check predicate on the "library_key" field. It's identical to LibraryKeyEQ.
func LibraryKey(v string) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldLibraryKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Rule {
	return predicate.Rule(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Rule {
	return predicate.Rule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Rule {
	return predicate.Rule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Rule {
	return predicate.Rule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Rule {
	return predicate.Rule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Rule {
	return predicate.Rule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Rule {
	return predicate.Rule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Rule {
	return predicate.Rule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Rule {
	return predicate.Rule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Rule {
	return predicate.Rule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Rule {
	return predicate.Rule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Rule {
	return predicate.Rule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Rule {
	return predicate.Rule(sql.FieldContainsFold(FieldName, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Rule {
	return predicate.Rule(sql.FieldNEQ(FieldEnabled, v))
}

// ConnectionIDEQ applies the EQ predicate on the "connection_id" field.
func ConnectionIDEQ(v int) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldConnectionID, v))
}

// ConnectionIDNEQ applies the NEQ predicate on the "connection_id" field.
func ConnectionIDNEQ(v int) predicate.Rule {
	return predicate.Rule(sql.FieldNEQ(FieldConnectionID, v))
}

// ConnectionIDIn applies the In predicate on the "connection_id" field.
func ConnectionIDIn(vs ...int) predicate.Rule {
	return predicate.Rule(sql.FieldIn(FieldConnectionID, vs...))
}

// ConnectionIDNotIn applies the NotIn predicate on the "connection_id" field.
func ConnectionIDNotIn(vs ...int) predicate.Rule {
	return predicate.Rule(sql.FieldNotIn(FieldConnectionID, vs...))
}

// LibraryKeyEQ applies the EQ predicate on the "library_key" field.
func LibraryKeyEQ(v string) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldLibraryKey, v))
}

// LibraryKeyNEQ applies the NEQ predicate on the "library_key" field.
func LibraryKeyNEQ(v string) predicate.Rule {
	return predicate.Rule(sql.FieldNEQ(FieldLibraryKey, v))
}

// LibraryKeyIn applies the In predicate on the "library_key" field.
func LibraryKeyIn(vs ...string) predicate.Rule {
	return predicate.Rule(sql.FieldIn(FieldLibraryKey, vs...))
}

// LibraryKeyNotIn applies the NotIn predicate on the "library_key" field.
func LibraryKeyNotIn(vs ...string) predicate.Rule {
	return predicate.Rule(sql.FieldNotIn(FieldLibraryKey, vs...))
}

// LibraryKeyGT applies the GT predicate on the "library_key" field.
func LibraryKeyGT(v string) predicate.Rule {
	return predicate.Rule(sql.FieldGT(FieldLibraryKey, v))
}

// LibraryKeyGTE applies the GTE predicate on the "library_key" field.
func LibraryKeyGTE(v string) predicate.Rule {
	return predicate.Rule(sql.FieldGTE(FieldLibraryKey, v))
}

// LibraryKeyLT applies the LT predicate on the "library_key" field.
func LibraryKeyLT(v string) predicate.Rule {
	return predicate.Rule(sql.FieldLT(FieldLibraryKey, v))
}

// LibraryKeyLTE applies the LTE predicate on the "library_key" field.
func LibraryKeyLTE(v string) predicate.Rule {
	return predicate.Rule(sql.FieldLTE(FieldLibraryKey, v))
}

// LibraryKeyContains applies the Contains predicate on the "library_key" field.
func LibraryKeyContains(v string) predicate.Rule {
	return predicate.Rule(sql.FieldContains(FieldLibraryKey, v))
}

// LibraryKeyHasPrefix applies the HasPrefix predicate on the "library_key" field.
func LibraryKeyHasPrefix(v string) predicate.Rule {
	return predicate.Rule(sql.FieldHasPrefix(FieldLibraryKey, v))
}

// LibraryKeyHasSuffix applies the HasSuffix predicate on the "library_key" field.
func LibraryKeyHasSuffix(v string) predicate.Rule {
	return predicate.Rule(sql.FieldHasSuffix(FieldLibraryKey, v))
}

// LibraryKeyEqualFold applies the EqualFold predicate on the "library_key" field.
func LibraryKeyEqualFold(v string) predicate.Rule {
	return predicate.Rule(sql.FieldEqualFold(FieldLibraryKey, v))
}

// LibraryKeyContainsFold applies the ContainsFold predicate on the "library_key" field.
func LibraryKeyContainsFold(v string) predicate.Rule {
	return predicate.Rule(sql.FieldContainsFold(FieldLibraryKey, v))
}

// GranularityEQ applies the EQ predicate on the "granularity" field.
func GranularityEQ(v Granularity) predicate.Rule {
	return predicate.Rule(sql.FieldEQ(FieldGranularity, v))
}

// GranularityNEQ applies the NEQ predicate on the "granularity" field.
func GranularityNEQ(v Granularity) predicate.Rule {
	return predicate.Rule(sql.FieldNEQ(FieldGranularity, v))
}

// GranularityIn applies the In predicate on the "granularity" field.
func GranularityIn(vs ...Granularity) predicate.Rule {
	return predicate.Rule(sql.FieldIn(FieldGranularity, vs...))
}

// GranularityNotIn applies the NotIn predicate on the "granularity" field.
func GranularityNotIn(vs ...Granularity) predicate.Rule {
	return predicate.Rule(sql.FieldNotIn(FieldGranularity, vs...))
}

// GranularityIsNil applies the IsNil predicate on the "granularity" field.
func GranularityIsNil() predicate.Rule {
	return predicate.Rule(sql.FieldIsNull(FieldGranularity))
}

// GranularityNotNil applies the NotNil predicate on the "granularity" field.
func GranularityNotNil() predicate.Rule {
	return predicate.Rule(sql.FieldNotNull(FieldGranularity))
}

// CriteriaIsNil applies the IsNil predicate on the "criteria" field.
func CriteriaIsNil() predicate.Rule {
	return predicate.Rule(sql.FieldIsNull(FieldCriteria))
}

// CriteriaNotNil applies the NotNil predicate on the "criteria" field.
func CriteriaNotNil() predicate.Rule {
	return predicate.Rule(sql.FieldNotNull(FieldCriteria))
}

// HasConnection applies the HasEdge predicate on the "connection" edge.
func HasConnection() predicate.Rule {
	return predicate.Rule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectionWith applies the HasEdge predicate on the "connection" edge with a given conditions (other predicates).
func HasConnectionWith(preds ...predicate.Connection) predicate.Rule {
	return predicate.Rule(func(s *sql.Selector) {
		step := newConnectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasActionSteps applies the HasEdge predicate on the "action_steps" edge.
func HasActionSteps() predicate.Rule {
	return predicate.Rule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ActionStepsTable, ActionStepsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasActionStepsWith applies the HasEdge predicate on the "action_steps" edge with a given conditions (other predicates).
func HasActionStepsWith(preds ...predicate.RuleActionStep) predicate.Rule {
	return predicate.Rule(func(s *sql.Selector) {
		step := newActionStepsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Rule) predicate.Rule {
	return predicate.Rule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Rule) predicate.Rule {
	return predicate.Rule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Rule) predicate.Rule {
	return predicate.Rule(sql.NotPredicates(p))
}
