// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Connection is the predicate function for connection builders.
type Connection func(*sql.Selector)

// Library is the predicate function for library builders.
type Library func(*sql.Selector)

// Rule is the predicate function for rule builders.
type Rule func(*sql.Selector)
