// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oom-killed/lib-managerr/ent/connection"
	"github.com/oom-killed/lib-managerr/ent/library"
	"github.com/oom-killed/lib-managerr/ent/predicate"
	"github.com/oom-killed/lib-managerr/ent/rule"
)

// ConnectionUpdate is the builder for updating Connection entities.
type ConnectionUpdate struct {
	config
	hooks    []Hook
	mutation *ConnectionMutation
}

// Where appends a list predicates to the ConnectionUpdate builder.
func (_u *ConnectionUpdate) Where(ps ...predicate.Connection) *ConnectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConnectionUpdate) SetUpdatedAt(v time.Time) *ConnectionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ConnectionUpdate) SetType(v connection.Type) *ConnectionUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConnectionUpdate) SetNillableType(v *connection.Type) *ConnectionUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ConnectionUpdate) SetName(v string) *ConnectionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConnectionUpdate) SetNillableName(v *string) *ConnectionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *ConnectionUpdate) SetHost(v string) *ConnectionUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ConnectionUpdate) SetNillableHost(v *string) *ConnectionUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ConnectionUpdate) SetPort(v int) *ConnectionUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ConnectionUpdate) SetNillablePort(v *int) *ConnectionUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ConnectionUpdate) AddPort(v int) *ConnectionUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// SetSsl sets the "ssl" field.
func (_u *ConnectionUpdate) SetSsl(v bool) *ConnectionUpdate {
	_u.mutation.SetSsl(v)
	return _u
}

// SetNillableSsl sets the "ssl" field if the given value is not nil.
func (_u *ConnectionUpdate) SetNillableSsl(v *bool) *ConnectionUpdate {
	if v != nil {
		_u.SetSsl(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *ConnectionUpdate) SetToken(v string) *ConnectionUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ConnectionUpdate) SetNillableToken(v *string) *ConnectionUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// AddLibraryIDs adds the "libraries" edge to the Library entity by IDs.
func (_u *ConnectionUpdate) AddLibraryIDs(ids ...int) *ConnectionUpdate {
	_u.mutation.AddLibraryIDs(ids...)
	return _u
}

// AddLibraries adds the "libraries" edges to the Library entity.
func (_u *ConnectionUpdate) AddLibraries(v ...*Library) *ConnectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLibraryIDs(ids...)
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (_u *ConnectionUpdate) AddRuleIDs(ids ...int) *ConnectionUpdate {
	_u.mutation.AddRuleIDs(ids...)
	return _u
}

// AddRules adds the "rules" edges to the Rule entity.
func (_u *ConnectionUpdate) AddRules(v ...*Rule) *ConnectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleIDs(ids...)
}

// Mutation returns the ConnectionMutation object of the builder.
func (_u *ConnectionUpdate) Mutation() *ConnectionMutation {
	return _u.mutation
}

// ClearLibraries clears all "libraries" edges to the Library entity.
func (_u *ConnectionUpdate) ClearLibraries() *ConnectionUpdate {
	_u.mutation.ClearLibraries()
	return _u
}

// RemoveLibraryIDs removes the "libraries" edge to Library entities by IDs.
func (_u *ConnectionUpdate) RemoveLibraryIDs(ids ...int) *ConnectionUpdate {
	_u.mutation.RemoveLibraryIDs(ids...)
	return _u
}

// RemoveLibraries removes "libraries" edges to Library entities.
func (_u *ConnectionUpdate) RemoveLibraries(v ...*Library) *ConnectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLibraryIDs(ids...)
}

// ClearRules clears all "rules" edges to the Rule entity.
func (_u *ConnectionUpdate) ClearRules() *ConnectionUpdate {
	_u.mutation.ClearRules()
	return _u
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (_u *ConnectionUpdate) RemoveRuleIDs(ids ...int) *ConnectionUpdate {
	_u.mutation.RemoveRuleIDs(ids...)
	return _u
}

// RemoveRules removes "rules" edges to Rule entities.
func (_u *ConnectionUpdate) RemoveRules(v ...*Rule) *ConnectionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConnectionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConnectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConnectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConnectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConnectionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := connection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConnectionUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := connection.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Connection.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := connection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Connection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := connection.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Connection.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Port(); ok {
		if err := connection.PortValidator(v); err != nil {
			return &ValidationError{Name: "port", err: fmt.Errorf(`ent: validator failed for field "Connection.port": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := connection.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Connection.token": %w`, err)}
		}
	}
	return nil
}

func (_u *ConnectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(connection.Table, connection.Columns, sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(connection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(connection.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(connection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(connection.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(connection.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(connection.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Ssl(); ok {
		_spec.SetField(connection.FieldSsl, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(connection.FieldToken, field.TypeString, value)
	}
	if _u.mutation.LibrariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.LibrariesTable,
			Columns: []string{connection.LibrariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLibrariesIDs(); len(nodes) > 0 && !_u.mutation.LibrariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.LibrariesTable,
			Columns: []string{connection.LibrariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LibrariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.LibrariesTable,
			Columns: []string{connection.LibrariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.RulesTable,
			Columns: []string{connection.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRulesIDs(); len(nodes) > 0 && !_u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.RulesTable,
			Columns: []string{connection.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.RulesTable,
			Columns: []string{connection.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{connection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConnectionUpdateOne is the builder for updating a single Connection entity.
type ConnectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConnectionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ConnectionUpdateOne) SetUpdatedAt(v time.Time) *ConnectionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetType sets the "type" field.
func (_u *ConnectionUpdateOne) SetType(v connection.Type) *ConnectionUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *ConnectionUpdateOne) SetNillableType(v *connection.Type) *ConnectionUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ConnectionUpdateOne) SetName(v string) *ConnectionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ConnectionUpdateOne) SetNillableName(v *string) *ConnectionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *ConnectionUpdateOne) SetHost(v string) *ConnectionUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ConnectionUpdateOne) SetNillableHost(v *string) *ConnectionUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ConnectionUpdateOne) SetPort(v int) *ConnectionUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ConnectionUpdateOne) SetNillablePort(v *int) *ConnectionUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ConnectionUpdateOne) AddPort(v int) *ConnectionUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// SetSsl sets the "ssl" field.
func (_u *ConnectionUpdateOne) SetSsl(v bool) *ConnectionUpdateOne {
	_u.mutation.SetSsl(v)
	return _u
}

// SetNillableSsl sets the "ssl" field if the given value is not nil.
func (_u *ConnectionUpdateOne) SetNillableSsl(v *bool) *ConnectionUpdateOne {
	if v != nil {
		_u.SetSsl(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *ConnectionUpdateOne) SetToken(v string) *ConnectionUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *ConnectionUpdateOne) SetNillableToken(v *string) *ConnectionUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// AddLibraryIDs adds the "libraries" edge to the Library entity by IDs.
func (_u *ConnectionUpdateOne) AddLibraryIDs(ids ...int) *ConnectionUpdateOne {
	_u.mutation.AddLibraryIDs(ids...)
	return _u
}

// AddLibraries adds the "libraries" edges to the Library entity.
func (_u *ConnectionUpdateOne) AddLibraries(v ...*Library) *ConnectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLibraryIDs(ids...)
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (_u *ConnectionUpdateOne) AddRuleIDs(ids ...int) *ConnectionUpdateOne {
	_u.mutation.AddRuleIDs(ids...)
	return _u
}

// AddRules adds the "rules" edges to the Rule entity.
func (_u *ConnectionUpdateOne) AddRules(v ...*Rule) *ConnectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRuleIDs(ids...)
}

// Mutation returns the ConnectionMutation object of the builder.
func (_u *ConnectionUpdateOne) Mutation() *ConnectionMutation {
	return _u.mutation
}

// ClearLibraries clears all "libraries" edges to the Library entity.
func (_u *ConnectionUpdateOne) ClearLibraries() *ConnectionUpdateOne {
	_u.mutation.ClearLibraries()
	return _u
}

// RemoveLibraryIDs removes the "libraries" edge to Library entities by IDs.
func (_u *ConnectionUpdateOne) RemoveLibraryIDs(ids ...int) *ConnectionUpdateOne {
	_u.mutation.RemoveLibraryIDs(ids...)
	return _u
}

// RemoveLibraries removes "libraries" edges to Library entities.
func (_u *ConnectionUpdateOne) RemoveLibraries(v ...*Library) *ConnectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLibraryIDs(ids...)
}

// ClearRules clears all "rules" edges to the Rule entity.
func (_u *ConnectionUpdateOne) ClearRules() *ConnectionUpdateOne {
	_u.mutation.ClearRules()
	return _u
}

// RemoveRuleIDs removes the "rules" edge to Rule entities by IDs.
func (_u *ConnectionUpdateOne) RemoveRuleIDs(ids ...int) *ConnectionUpdateOne {
	_u.mutation.RemoveRuleIDs(ids...)
	return _u
}

// RemoveRules removes "rules" edges to Rule entities.
func (_u *ConnectionUpdateOne) RemoveRules(v ...*Rule) *ConnectionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRuleIDs(ids...)
}

// Where appends a list predicates to the ConnectionUpdate builder.
func (_u *ConnectionUpdateOne) Where(ps ...predicate.Connection) *ConnectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConnectionUpdateOne) Select(field string, fields ...string) *ConnectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Connection entity.
func (_u *ConnectionUpdateOne) Save(ctx context.Context) (*Connection, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConnectionUpdateOne) SaveX(ctx context.Context) *Connection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConnectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConnectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ConnectionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := connection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConnectionUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := connection.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Connection.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := connection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Connection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := connection.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Connection.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Port(); ok {
		if err := connection.PortValidator(v); err != nil {
			return &ValidationError{Name: "port", err: fmt.Errorf(`ent: validator failed for field "Connection.port": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Token(); ok {
		if err := connection.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Connection.token": %w`, err)}
		}
	}
	return nil
}

func (_u *ConnectionUpdateOne) sqlSave(ctx context.Context) (_node *Connection, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(connection.Table, connection.Columns, sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Connection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, connection.FieldID)
		for _, f := range fields {
			if !connection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != connection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(connection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(connection.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(connection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(connection.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(connection.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(connection.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Ssl(); ok {
		_spec.SetField(connection.FieldSsl, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(connection.FieldToken, field.TypeString, value)
	}
	if _u.mutation.LibrariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.LibrariesTable,
			Columns: []string{connection.LibrariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLibrariesIDs(); len(nodes) > 0 && !_u.mutation.LibrariesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.LibrariesTable,
			Columns: []string{connection.LibrariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LibrariesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.LibrariesTable,
			Columns: []string{connection.LibrariesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(library.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.RulesTable,
			Columns: []string{connection.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRulesIDs(); len(nodes) > 0 && !_u.mutation.RulesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.RulesTable,
			Columns: []string{connection.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connection.RulesTable,
			Columns: []string{connection.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Connection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{connection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
