// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/oom-killed/lib-managerr/ent/connection"
)

// Connection is the model entity for the Connection schema.
type Connection struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Type holds the value of the "type" field.
	Type connection.Type `json:"type,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Host holds the value of the "host" field.
	Host string `json:"host,omitempty"`
	// Port holds the value of the "port" field.
	Port int `json:"port,omitempty"`
	// Ssl holds the value of the "ssl" field.
	Ssl bool `json:"ssl,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConnectionQuery when eager-loading is set.
	Edges        ConnectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConnectionEdges holds the relations/edges for other nodes in the graph.
type ConnectionEdges struct {
	// Libraries holds the value of the libraries edge.
	Libraries []*Library `json:"libraries,omitempty"`
	// Rules holds the value of the rules edge.
	Rules []*Rule `json:"rules,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// LibrariesOrErr returns the Libraries value or an error if the edge
// was not loaded in eager-loading.
func (e ConnectionEdges) LibrariesOrErr() ([]*Library, error) {
	if e.loadedTypes[0] {
		return e.Libraries, nil
	}
	return nil, &NotLoadedError{edge: "libraries"}
}

// RulesOrErr returns the Rules value or an error if the edge
// was not loaded in eager-loading.
func (e ConnectionEdges) RulesOrErr() ([]*Rule, error) {
	if e.loadedTypes[1] {
		return e.Rules, nil
	}
	return nil, &NotLoadedError{edge: "rules"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Connection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case connection.FieldSsl:
			values[i] = new(sql.NullBool)
		case connection.FieldID, connection.FieldPort:
			values[i] = new(sql.NullInt64)
		case connection.FieldType, connection.FieldName, connection.FieldHost, connection.FieldToken:
			values[i] = new(sql.NullString)
		case connection.FieldCreatedAt, connection.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Connection fields.
func (_m *Connection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case connection.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case connection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case connection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case connection.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = connection.Type(value.String)
			}
		case connection.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case connection.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case connection.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case connection.FieldSsl:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field ssl", values[i])
			} else if value.Valid {
				_m.Ssl = value.Bool
			}
		case connection.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Connection.
// This includes values selected through modifiers, order, etc.
func (_m *Connection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLibraries queries the "libraries" edge of the Connection entity.
func (_m *Connection) QueryLibraries() *LibraryQuery {
	return NewConnectionClient(_m.config).QueryLibraries(_m)
}

// QueryRules queries the "rules" edge of the Connection entity.
func (_m *Connection) QueryRules() *RuleQuery {
	return NewConnectionClient(_m.config).QueryRules(_m)
}

// Update returns a builder for updating this Connection.
// Note that you need to call Connection.Unwrap() before calling this method if this Connection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Connection) Update() *ConnectionUpdateOne {
	return NewConnectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Connection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Connection) Unwrap() *Connection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Connection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Connection) String() string {
	var builder strings.Builder
	builder.WriteString("Connection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	builder.WriteString("ssl=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ssl))
	builder.WriteString(", ")
	builder.WriteString("token=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// Connections is a parsable slice of Connection.
type Connections []*Connection
