// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oom-killed/lib-managerr/ent/connection"
	"github.com/oom-killed/lib-managerr/ent/library"
)

// LibraryCreate is the builder for creating a Library entity.
type LibraryCreate struct {
	config
	mutation *LibraryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *LibraryCreate) SetCreatedAt(v time.Time) *LibraryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LibraryCreate) SetNillableCreatedAt(v *time.Time) *LibraryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LibraryCreate) SetUpdatedAt(v time.Time) *LibraryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LibraryCreate) SetNillableUpdatedAt(v *time.Time) *LibraryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExternalID sets the "external_id" field.
func (_c *LibraryCreate) SetExternalID(v string) *LibraryCreate {
	_c.mutation.SetExternalID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *LibraryCreate) SetTitle(v string) *LibraryCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetMediaType sets the "media_type" field.
func (_c *LibraryCreate) SetMediaType(v library.MediaType) *LibraryCreate {
	_c.mutation.SetMediaType(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *LibraryCreate) SetEnabled(v bool) *LibraryCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *LibraryCreate) SetNillableEnabled(v *bool) *LibraryCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetConnectionID sets the "connection" edge to the Connection entity by ID.
func (_c *LibraryCreate) SetConnectionID(id int) *LibraryCreate {
	_c.mutation.SetConnectionID(id)
	return _c
}

// SetConnection sets the "connection" edge to the Connection entity.
func (_c *LibraryCreate) SetConnection(v *Connection) *LibraryCreate {
	return _c.SetConnectionID(v.ID)
}

// Mutation returns the LibraryMutation object of the builder.
func (_c *LibraryCreate) Mutation() *LibraryMutation {
	return _c.mutation
}

// Save creates the Library in the database.
func (_c *LibraryCreate) Save(ctx context.Context) (*Library, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LibraryCreate) SaveX(ctx context.Context) *Library {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LibraryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LibraryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LibraryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := library.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := library.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := library.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LibraryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Library.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Library.updated_at"`)}
	}
	if _, ok := _c.mutation.ExternalID(); !ok {
		return &ValidationError{Name: "external_id", err: errors.New(`ent: missing required field "Library.external_id"`)}
	}
	if v, ok := _c.mutation.ExternalID(); ok {
		if err := library.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Library.external_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Library.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := library.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Library.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MediaType(); !ok {
		return &ValidationError{Name: "media_type", err: errors.New(`ent: missing required field "Library.media_type"`)}
	}
	if v, ok := _c.mutation.MediaType(); ok {
		if err := library.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "Library.media_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Library.enabled"`)}
	}
	if len(_c.mutation.ConnectionIDs()) == 0 {
		return &ValidationError{Name: "connection", err: errors.New(`ent: missing required edge "Library.connection"`)}
	}
	return nil
}

func (_c *LibraryCreate) sqlSave(ctx context.Context) (*Library, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LibraryCreate) createSpec() (*Library, *sqlgraph.CreateSpec) {
	var (
		_node = &Library{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(library.Table, sqlgraph.NewFieldSpec(library.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(library.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(library.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExternalID(); ok {
		_spec.SetField(library.FieldExternalID, field.TypeString, value)
		_node.ExternalID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(library.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.MediaType(); ok {
		_spec.SetField(library.FieldMediaType, field.TypeEnum, value)
		_node.MediaType = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(library.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := _c.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   library.ConnectionTable,
			Columns: []string{library.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.connection_libraries = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LibraryCreateBulk is the builder for creating many Library entities in bulk.
type LibraryCreateBulk struct {
	config
	err      error
	builders []*LibraryCreate
}

// Save creates the Library entities in the database.
func (_c *LibraryCreateBulk) Save(ctx context.Context) ([]*Library, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Library, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LibraryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LibraryCreateBulk) SaveX(ctx context.Context) []*Library {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LibraryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LibraryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
