// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oom-killed/lib-managerr/ent/connection"
	"github.com/oom-killed/lib-managerr/ent/library"
	"github.com/oom-killed/lib-managerr/ent/predicate"
)

// LibraryUpdate is the builder for updating Library entities.
type LibraryUpdate struct {
	config
	hooks    []Hook
	mutation *LibraryMutation
}

// Where appends a list predicates to the LibraryUpdate builder.
func (_u *LibraryUpdate) Where(ps ...predicate.Library) *LibraryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibraryUpdate) SetUpdatedAt(v time.Time) *LibraryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *LibraryUpdate) SetExternalID(v string) *LibraryUpdate {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableExternalID(v *string) *LibraryUpdate {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *LibraryUpdate) SetTitle(v string) *LibraryUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableTitle(v *string) *LibraryUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *LibraryUpdate) SetMediaType(v library.MediaType) *LibraryUpdate {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableMediaType(v *library.MediaType) *LibraryUpdate {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LibraryUpdate) SetEnabled(v bool) *LibraryUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LibraryUpdate) SetNillableEnabled(v *bool) *LibraryUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConnectionID sets the "connection" edge to the Connection entity by ID.
func (_u *LibraryUpdate) SetConnectionID(id int) *LibraryUpdate {
	_u.mutation.SetConnectionID(id)
	return _u
}

// SetConnection sets the "connection" edge to the Connection entity.
func (_u *LibraryUpdate) SetConnection(v *Connection) *LibraryUpdate {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the LibraryMutation object of the builder.
func (_u *LibraryUpdate) Mutation() *LibraryMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the Connection entity.
func (_u *LibraryUpdate) ClearConnection() *LibraryUpdate {
	_u.mutation.ClearConnection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LibraryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibraryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LibraryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibraryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibraryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := library.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibraryUpdate) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := library.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Library.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := library.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Library.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaType(); ok {
		if err := library.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "Library.media_type": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Library.connection"`)
	}
	return nil
}

func (_u *LibraryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(library.Table, library.Columns, sqlgraph.NewFieldSpec(library.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(library.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(library.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(library.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(library.FieldMediaType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(library.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   library.ConnectionTable,
			Columns: []string{library.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   library.ConnectionTable,
			Columns: []string{library.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{library.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LibraryUpdateOne is the builder for updating a single Library entity.
type LibraryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LibraryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibraryUpdateOne) SetUpdatedAt(v time.Time) *LibraryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExternalID sets the "external_id" field.
func (_u *LibraryUpdateOne) SetExternalID(v string) *LibraryUpdateOne {
	_u.mutation.SetExternalID(v)
	return _u
}

// SetNillableExternalID sets the "external_id" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableExternalID(v *string) *LibraryUpdateOne {
	if v != nil {
		_u.SetExternalID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *LibraryUpdateOne) SetTitle(v string) *LibraryUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableTitle(v *string) *LibraryUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetMediaType sets the "media_type" field.
func (_u *LibraryUpdateOne) SetMediaType(v library.MediaType) *LibraryUpdateOne {
	_u.mutation.SetMediaType(v)
	return _u
}

// SetNillableMediaType sets the "media_type" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableMediaType(v *library.MediaType) *LibraryUpdateOne {
	if v != nil {
		_u.SetMediaType(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LibraryUpdateOne) SetEnabled(v bool) *LibraryUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LibraryUpdateOne) SetNillableEnabled(v *bool) *LibraryUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetConnectionID sets the "connection" edge to the Connection entity by ID.
func (_u *LibraryUpdateOne) SetConnectionID(id int) *LibraryUpdateOne {
	_u.mutation.SetConnectionID(id)
	return _u
}

// SetConnection sets the "connection" edge to the Connection entity.
func (_u *LibraryUpdateOne) SetConnection(v *Connection) *LibraryUpdateOne {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the LibraryMutation object of the builder.
func (_u *LibraryUpdateOne) Mutation() *LibraryMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the Connection entity.
func (_u *LibraryUpdateOne) ClearConnection() *LibraryUpdateOne {
	_u.mutation.ClearConnection()
	return _u
}

// Where appends a list predicates to the LibraryUpdate builder.
func (_u *LibraryUpdateOne) Where(ps ...predicate.Library) *LibraryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LibraryUpdateOne) Select(field string, fields ...string) *LibraryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Library entity.
func (_u *LibraryUpdateOne) Save(ctx context.Context) (*Library, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibraryUpdateOne) SaveX(ctx context.Context) *Library {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LibraryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibraryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibraryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := library.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibraryUpdateOne) check() error {
	if v, ok := _u.mutation.ExternalID(); ok {
		if err := library.ExternalIDValidator(v); err != nil {
			return &ValidationError{Name: "external_id", err: fmt.Errorf(`ent: validator failed for field "Library.external_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := library.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Library.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaType(); ok {
		if err := library.MediaTypeValidator(v); err != nil {
			return &ValidationError{Name: "media_type", err: fmt.Errorf(`ent: validator failed for field "Library.media_type": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Library.connection"`)
	}
	return nil
}

func (_u *LibraryUpdateOne) sqlSave(ctx context.Context) (_node *Library, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(library.Table, library.Columns, sqlgraph.NewFieldSpec(library.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Library.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, library.FieldID)
		for _, f := range fields {
			if !library.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != library.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(library.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExternalID(); ok {
		_spec.SetField(library.FieldExternalID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(library.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.MediaType(); ok {
		_spec.SetField(library.FieldMediaType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(library.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   library.ConnectionTable,
			Columns: []string{library.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   library.ConnectionTable,
			Columns: []string{library.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Library{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{library.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
