// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/oom-killed/lib-managerr/ent/connection"
	"github.com/oom-killed/lib-managerr/ent/library"
	"github.com/oom-killed/lib-managerr/ent/predicate"
	"github.com/oom-killed/lib-managerr/ent/rule"
	"github.com/oom-killed/lib-managerr/ent/ruleactionstep"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeConnection     = "Connection"
	TypeLibrary        = "Library"
	TypeRule           = "Rule"
	TypeRuleActionStep = "RuleActionStep"
)

// ConnectionMutation represents an operation that mutates the Connection nodes in the graph.
type ConnectionMutation struct {
	config
	op               Op
	typ              string
	id               *int
	created_at       *time.Time
	updated_at       *time.Time
	_type            *connection.Type
	name             *string
	host             *string
	port             *int
	addport          *int
	ssl              *bool
	token            *string
	clearedFields    map[string]struct{}
	libraries        map[int]struct{}
	removedlibraries map[int]struct{}
	clearedlibraries bool
	rules            map[int]struct{}
	removedrules     map[int]struct{}
	clearedrules     bool
	done             bool
	oldValue         func(context.Context) (*Connection, error)
	predicates       []predicate.Connection
}

var _ ent.Mutation = (*ConnectionMutation)(nil)

// connectionOption allows management of the mutation configuration using functional options.
type connectionOption func(*ConnectionMutation)

// newConnectionMutation creates new mutation for the Connection entity.
func newConnectionMutation(c config, op Op, opts ...connectionOption) *ConnectionMutation {
	m := &ConnectionMutation{
		config:        c,
		op:            op,
		typ:           TypeConnection,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withConnectionID sets the ID field of the mutation.
func withConnectionID(id int) connectionOption {
	return func(m *ConnectionMutation) {
		var (
			err   error
			once  sync.Once
			value *Connection
		)
		m.oldValue = func(ctx context.Context) (*Connection, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Connection.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withConnection sets the old Connection of the mutation.
func withConnection(node *Connection) connectionOption {
	return func(m *ConnectionMutation) {
		m.oldValue = func(context.Context) (*Connection, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m ConnectionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m ConnectionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *ConnectionMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *ConnectionMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Connection.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *ConnectionMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *ConnectionMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Connection entity.
// If the Connection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *ConnectionMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *ConnectionMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *ConnectionMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Connection entity.
// If the Connection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *ConnectionMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetType sets the "type" field.
func (m *ConnectionMutation) SetType(c connection.Type) {
	m._type = &c
}

// GetType returns the value of the "type" field in the mutation.
func (m *ConnectionMutation) GetType() (r connection.Type, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the Connection entity.
// If the Connection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionMutation) OldType(ctx context.Context) (v connection.Type, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// ResetType resets all changes to the "type" field.
func (m *ConnectionMutation) ResetType() {
	m._type = nil
}

// SetName sets the "name" field.
func (m *ConnectionMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *ConnectionMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Connection entity.
// If the Connection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *ConnectionMutation) ResetName() {
	m.name = nil
}

// SetHost sets the "host" field.
func (m *ConnectionMutation) SetHost(s string) {
	m.host = &s
}

// Host returns the value of the "host" field in the mutation.
func (m *ConnectionMutation) Host() (r string, exists bool) {
	v := m.host
	if v == nil {
		return
	}
	return *v, true
}

// OldHost returns the old "host" field's value of the Connection entity.
// If the Connection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionMutation) OldHost(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHost is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHost requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHost: %w", err)
	}
	return oldValue.Host, nil
}

// ResetHost resets all changes to the "host" field.
func (m *ConnectionMutation) ResetHost() {
	m.host = nil
}

// SetPort sets the "port" field.
func (m *ConnectionMutation) SetPort(i int) {
	m.port = &i
	m.addport = nil
}

// Port returns the value of the "port" field in the mutation.
func (m *ConnectionMutation) Port() (r int, exists bool) {
	v := m.port
	if v == nil {
		return
	}
	return *v, true
}

// OldPort returns the old "port" field's value of the Connection entity.
// If the Connection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionMutation) OldPort(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPort is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPort requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPort: %w", err)
	}
	return oldValue.Port, nil
}

// AddPort adds i to the "port" field.
func (m *ConnectionMutation) AddPort(i int) {
	if m.addport != nil {
		*m.addport += i
	} else {
		m.addport = &i
	}
}

// AddedPort returns the value that was added to the "port" field in this mutation.
func (m *ConnectionMutation) AddedPort() (r int, exists bool) {
	v := m.addport
	if v == nil {
		return
	}
	return *v, true
}

// ResetPort resets all changes to the "port" field.
func (m *ConnectionMutation) ResetPort() {
	m.port = nil
	m.addport = nil
}

// SetSsl sets the "ssl" field.
func (m *ConnectionMutation) SetSsl(b bool) {
	m.ssl = &b
}

// Ssl returns the value of the "ssl" field in the mutation.
func (m *ConnectionMutation) Ssl() (r bool, exists bool) {
	v := m.ssl
	if v == nil {
		return
	}
	return *v, true
}

// OldSsl returns the old "ssl" field's value of the Connection entity.
// If the Connection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionMutation) OldSsl(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSsl is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSsl requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSsl: %w", err)
	}
	return oldValue.Ssl, nil
}

// ResetSsl resets all changes to the "ssl" field.
func (m *ConnectionMutation) ResetSsl() {
	m.ssl = nil
}

// SetToken sets the "token" field.
func (m *ConnectionMutation) SetToken(s string) {
	m.token = &s
}

// Token returns the value of the "token" field in the mutation.
func (m *ConnectionMutation) Token() (r string, exists bool) {
	v := m.token
	if v == nil {
		return
	}
	return *v, true
}

// OldToken returns the old "token" field's value of the Connection entity.
// If the Connection object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *ConnectionMutation) OldToken(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldToken is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldToken requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldToken: %w", err)
	}
	return oldValue.Token, nil
}

// ResetToken resets all changes to the "token" field.
func (m *ConnectionMutation) ResetToken() {
	m.token = nil
}

// AddLibraryIDs adds the "libraries" edge to the Library entity by ids.
func (m *ConnectionMutation) AddLibraryIDs(ids ...int) {
	if m.libraries == nil {
		m.libraries = make(map[int]struct{})
	}
	for i := range ids {
		m.libraries[ids[i]] = struct{}{}
	}
}

// ClearLibraries clears the "libraries" edge to the Library entity.
func (m *ConnectionMutation) ClearLibraries() {
	m.clearedlibraries = true
}

// LibrariesCleared reports if the "libraries" edge to the Library entity was cleared.
func (m *ConnectionMutation) LibrariesCleared() bool {
	return m.clearedlibraries
}

// RemoveLibraryIDs removes the "libraries" edge to the Library entity by IDs.
func (m *ConnectionMutation) RemoveLibraryIDs(ids ...int) {
	if m.removedlibraries == nil {
		m.removedlibraries = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.libraries, ids[i])
		m.removedlibraries[ids[i]] = struct{}{}
	}
}

// RemovedLibraries returns the removed IDs of the "libraries" edge to the Library entity.
func (m *ConnectionMutation) RemovedLibrariesIDs() (ids []int) {
	for id := range m.removedlibraries {
		ids = append(ids, id)
	}
	return
}

// LibrariesIDs returns the "libraries" edge IDs in the mutation.
func (m *ConnectionMutation) LibrariesIDs() (ids []int) {
	for id := range m.libraries {
		ids = append(ids, id)
	}
	return
}

// ResetLibraries resets all changes to the "libraries" edge.
func (m *ConnectionMutation) ResetLibraries() {
	m.libraries = nil
	m.clearedlibraries = false
	m.removedlibraries = nil
}

// AddRuleIDs adds the "rules" edge to the Rule entity by ids.
func (m *ConnectionMutation) AddRuleIDs(ids ...int) {
	if m.rules == nil {
		m.rules = make(map[int]struct{})
	}
	for i := range ids {
		m.rules[ids[i]] = struct{}{}
	}
}

// ClearRules clears the "rules" edge to the Rule entity.
func (m *ConnectionMutation) ClearRules() {
	m.clearedrules = true
}

// RulesCleared reports if the "rules" edge to the Rule entity was cleared.
func (m *ConnectionMutation) RulesCleared() bool {
	return m.clearedrules
}

// RemoveRuleIDs removes the "rules" edge to the Rule entity by IDs.
func (m *ConnectionMutation) RemoveRuleIDs(ids ...int) {
	if m.removedrules == nil {
		m.removedrules = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.rules, ids[i])
		m.removedrules[ids[i]] = struct{}{}
	}
}

// RemovedRules returns the removed IDs of the "rules" edge to the Rule entity.
func (m *ConnectionMutation) RemovedRulesIDs() (ids []int) {
	for id := range m.removedrules {
		ids = append(ids, id)
	}
	return
}

// RulesIDs returns the "rules" edge IDs in the mutation.
func (m *ConnectionMutation) RulesIDs() (ids []int) {
	for id := range m.rules {
		ids = append(ids, id)
	}
	return
}

// ResetRules resets all changes to the "rules" edge.
func (m *ConnectionMutation) ResetRules() {
	m.rules = nil
	m.clearedrules = false
	m.removedrules = nil
}

// Where appends a list predicates to the ConnectionMutation builder.
func (m *ConnectionMutation) Where(ps ...predicate.Connection) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the ConnectionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *ConnectionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Connection, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *ConnectionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *ConnectionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Connection).
func (m *ConnectionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *ConnectionMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.created_at != nil {
		fields = append(fields, connection.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, connection.FieldUpdatedAt)
	}
	if m._type != nil {
		fields = append(fields, connection.FieldType)
	}
	if m.name != nil {
		fields = append(fields, connection.FieldName)
	}
	if m.host != nil {
		fields = append(fields, connection.FieldHost)
	}
	if m.port != nil {
		fields = append(fields, connection.FieldPort)
	}
	if m.ssl != nil {
		fields = append(fields, connection.FieldSsl)
	}
	if m.token != nil {
		fields = append(fields, connection.FieldToken)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *ConnectionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case connection.FieldCreatedAt:
		return m.CreatedAt()
	case connection.FieldUpdatedAt:
		return m.UpdatedAt()
	case connection.FieldType:
		return m.GetType()
	case connection.FieldName:
		return m.Name()
	case connection.FieldHost:
		return m.Host()
	case connection.FieldPort:
		return m.Port()
	case connection.FieldSsl:
		return m.Ssl()
	case connection.FieldToken:
		return m.Token()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *ConnectionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case connection.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case connection.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case connection.FieldType:
		return m.OldType(ctx)
	case connection.FieldName:
		return m.OldName(ctx)
	case connection.FieldHost:
		return m.OldHost(ctx)
	case connection.FieldPort:
		return m.OldPort(ctx)
	case connection.FieldSsl:
		return m.OldSsl(ctx)
	case connection.FieldToken:
		return m.OldToken(ctx)
	}
	return nil, fmt.Errorf("unknown Connection field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ConnectionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case connection.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case connection.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case connection.FieldType:
		v, ok := value.(connection.Type)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case connection.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case connection.FieldHost:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHost(v)
		return nil
	case connection.FieldPort:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPort(v)
		return nil
	case connection.FieldSsl:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSsl(v)
		return nil
	case connection.FieldToken:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetToken(v)
		return nil
	}
	return fmt.Errorf("unknown Connection field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *ConnectionMutation) AddedFields() []string {
	var fields []string
	if m.addport != nil {
		fields = append(fields, connection.FieldPort)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *ConnectionMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case connection.FieldPort:
		return m.AddedPort()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *ConnectionMutation) AddField(name string, value ent.Value) error {
	switch name {
	case connection.FieldPort:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPort(v)
		return nil
	}
	return fmt.Errorf("unknown Connection numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *ConnectionMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *ConnectionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *ConnectionMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Connection nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *ConnectionMutation) ResetField(name string) error {
	switch name {
	case connection.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case connection.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case connection.FieldType:
		m.ResetType()
		return nil
	case connection.FieldName:
		m.ResetName()
		return nil
	case connection.FieldHost:
		m.ResetHost()
		return nil
	case connection.FieldPort:
		m.ResetPort()
		return nil
	case connection.FieldSsl:
		m.ResetSsl()
		return nil
	case connection.FieldToken:
		m.ResetToken()
		return nil
	}
	return fmt.Errorf("unknown Connection field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *ConnectionMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.libraries != nil {
		edges = append(edges, connection.EdgeLibraries)
	}
	if m.rules != nil {
		edges = append(edges, connection.EdgeRules)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *ConnectionMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case connection.EdgeLibraries:
		ids := make([]ent.Value, 0, len(m.libraries))
		for id := range m.libraries {
			ids = append(ids, id)
		}
		return ids
	case connection.EdgeRules:
		ids := make([]ent.Value, 0, len(m.rules))
		for id := range m.rules {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *ConnectionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedlibraries != nil {
		edges = append(edges, connection.EdgeLibraries)
	}
	if m.removedrules != nil {
		edges = append(edges, connection.EdgeRules)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *ConnectionMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case connection.EdgeLibraries:
		ids := make([]ent.Value, 0, len(m.removedlibraries))
		for id := range m.removedlibraries {
			ids = append(ids, id)
		}
		return ids
	case connection.EdgeRules:
		ids := make([]ent.Value, 0, len(m.removedrules))
		for id := range m.removedrules {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *ConnectionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedlibraries {
		edges = append(edges, connection.EdgeLibraries)
	}
	if m.clearedrules {
		edges = append(edges, connection.EdgeRules)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *ConnectionMutation) EdgeCleared(name string) bool {
	switch name {
	case connection.EdgeLibraries:
		return m.clearedlibraries
	case connection.EdgeRules:
		return m.clearedrules
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *ConnectionMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Connection unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *ConnectionMutation) ResetEdge(name string) error {
	switch name {
	case connection.EdgeLibraries:
		m.ResetLibraries()
		return nil
	case connection.EdgeRules:
		m.ResetRules()
		return nil
	}
	return fmt.Errorf("unknown Connection edge %s", name)
}

// LibraryMutation represents an operation that mutates the Library nodes in the graph.
type LibraryMutation struct {
	config
	op                Op
	typ               string
	id                *int
	created_at        *time.Time
	updated_at        *time.Time
	external_id       *string
	title             *string
	media_type        *library.MediaType
	enabled           *bool
	clearedFields     map[string]struct{}
	connection        *int
	clearedconnection bool
	done              bool
	oldValue          func(context.Context) (*Library, error)
	predicates        []predicate.Library
}

var _ ent.Mutation = (*LibraryMutation)(nil)

// libraryOption allows management of the mutation configuration using functional options.
type libraryOption func(*LibraryMutation)

// newLibraryMutation creates new mutation for the Library entity.
func newLibraryMutation(c config, op Op, opts ...libraryOption) *LibraryMutation {
	m := &LibraryMutation{
		config:        c,
		op:            op,
		typ:           TypeLibrary,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withLibraryID sets the ID field of the mutation.
func withLibraryID(id int) libraryOption {
	return func(m *LibraryMutation) {
		var (
			err   error
			once  sync.Once
			value *Library
		)
		m.oldValue = func(ctx context.Context) (*Library, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Library.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withLibrary sets the old Library of the mutation.
func withLibrary(node *Library) libraryOption {
	return func(m *LibraryMutation) {
		m.oldValue = func(context.Context) (*Library, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m LibraryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m LibraryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *LibraryMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *LibraryMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Library.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *LibraryMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *LibraryMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Library entity.
// If the Library object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LibraryMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *LibraryMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *LibraryMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *LibraryMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Library entity.
// If the Library object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LibraryMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *LibraryMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetExternalID sets the "external_id" field.
func (m *LibraryMutation) SetExternalID(s string) {
	m.external_id = &s
}

// ExternalID returns the value of the "external_id" field in the mutation.
func (m *LibraryMutation) ExternalID() (r string, exists bool) {
	v := m.external_id
	if v == nil {
		return
	}
	return *v, true
}

// OldExternalID returns the old "external_id" field's value of the Library entity.
// If the Library object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LibraryMutation) OldExternalID(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExternalID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExternalID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExternalID: %w", err)
	}
	return oldValue.ExternalID, nil
}

// ResetExternalID resets all changes to the "external_id" field.
func (m *LibraryMutation) ResetExternalID() {
	m.external_id = nil
}

// SetTitle sets the "title" field.
func (m *LibraryMutation) SetTitle(s string) {
	m.title = &s
}

// Title returns the value of the "title" field in the mutation.
func (m *LibraryMutation) Title() (r string, exists bool) {
	v := m.title
	if v == nil {
		return
	}
	return *v, true
}

// OldTitle returns the old "title" field's value of the Library entity.
// If the Library object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LibraryMutation) OldTitle(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTitle is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTitle requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTitle: %w", err)
	}
	return oldValue.Title, nil
}

// ResetTitle resets all changes to the "title" field.
func (m *LibraryMutation) ResetTitle() {
	m.title = nil
}

// SetMediaType sets the "media_type" field.
func (m *LibraryMutation) SetMediaType(lt library.MediaType) {
	m.media_type = &lt
}

// MediaType returns the value of the "media_type" field in the mutation.
func (m *LibraryMutation) MediaType() (r library.MediaType, exists bool) {
	v := m.media_type
	if v == nil {
		return
	}
	return *v, true
}

// OldMediaType returns the old "media_type" field's value of the Library entity.
// If the Library object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LibraryMutation) OldMediaType(ctx context.Context) (v library.MediaType, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMediaType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMediaType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMediaType: %w", err)
	}
	return oldValue.MediaType, nil
}

// ResetMediaType resets all changes to the "media_type" field.
func (m *LibraryMutation) ResetMediaType() {
	m.media_type = nil
}

// SetEnabled sets the "enabled" field.
func (m *LibraryMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *LibraryMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the Library entity.
// If the Library object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *LibraryMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *LibraryMutation) ResetEnabled() {
	m.enabled = nil
}

// SetConnectionID sets the "connection" edge to the Connection entity by id.
func (m *LibraryMutation) SetConnectionID(id int) {
	m.connection = &id
}

// ClearConnection clears the "connection" edge to the Connection entity.
func (m *LibraryMutation) ClearConnection() {
	m.clearedconnection = true
}

// ConnectionCleared reports if the "connection" edge to the Connection entity was cleared.
func (m *LibraryMutation) ConnectionCleared() bool {
	return m.clearedconnection
}

// ConnectionID returns the "connection" edge ID in the mutation.
func (m *LibraryMutation) ConnectionID() (id int, exists bool) {
	if m.connection != nil {
		return *m.connection, true
	}
	return
}

// ConnectionIDs returns the "connection" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ConnectionID instead. It exists only for internal usage by the builders.
func (m *LibraryMutation) ConnectionIDs() (ids []int) {
	if id := m.connection; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetConnection resets all changes to the "connection" edge.
func (m *LibraryMutation) ResetConnection() {
	m.connection = nil
	m.clearedconnection = false
}

// Where appends a list predicates to the LibraryMutation builder.
func (m *LibraryMutation) Where(ps ...predicate.Library) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the LibraryMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *LibraryMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Library, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *LibraryMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *LibraryMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Library).
func (m *LibraryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *LibraryMutation) Fields() []string {
	fields := make([]string, 0, 6)
	if m.created_at != nil {
		fields = append(fields, library.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, library.FieldUpdatedAt)
	}
	if m.external_id != nil {
		fields = append(fields, library.FieldExternalID)
	}
	if m.title != nil {
		fields = append(fields, library.FieldTitle)
	}
	if m.media_type != nil {
		fields = append(fields, library.FieldMediaType)
	}
	if m.enabled != nil {
		fields = append(fields, library.FieldEnabled)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *LibraryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case library.FieldCreatedAt:
		return m.CreatedAt()
	case library.FieldUpdatedAt:
		return m.UpdatedAt()
	case library.FieldExternalID:
		return m.ExternalID()
	case library.FieldTitle:
		return m.Title()
	case library.FieldMediaType:
		return m.MediaType()
	case library.FieldEnabled:
		return m.Enabled()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *LibraryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case library.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case library.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case library.FieldExternalID:
		return m.OldExternalID(ctx)
	case library.FieldTitle:
		return m.OldTitle(ctx)
	case library.FieldMediaType:
		return m.OldMediaType(ctx)
	case library.FieldEnabled:
		return m.OldEnabled(ctx)
	}
	return nil, fmt.Errorf("unknown Library field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LibraryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case library.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case library.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case library.FieldExternalID:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExternalID(v)
		return nil
	case library.FieldTitle:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTitle(v)
		return nil
	case library.FieldMediaType:
		v, ok := value.(library.MediaType)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMediaType(v)
		return nil
	case library.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	}
	return fmt.Errorf("unknown Library field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *LibraryMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *LibraryMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *LibraryMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Library numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *LibraryMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *LibraryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *LibraryMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Library nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *LibraryMutation) ResetField(name string) error {
	switch name {
	case library.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case library.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case library.FieldExternalID:
		m.ResetExternalID()
		return nil
	case library.FieldTitle:
		m.ResetTitle()
		return nil
	case library.FieldMediaType:
		m.ResetMediaType()
		return nil
	case library.FieldEnabled:
		m.ResetEnabled()
		return nil
	}
	return fmt.Errorf("unknown Library field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *LibraryMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.connection != nil {
		edges = append(edges, library.EdgeConnection)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *LibraryMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case library.EdgeConnection:
		if id := m.connection; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *LibraryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *LibraryMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *LibraryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedconnection {
		edges = append(edges, library.EdgeConnection)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *LibraryMutation) EdgeCleared(name string) bool {
	switch name {
	case library.EdgeConnection:
		return m.clearedconnection
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *LibraryMutation) ClearEdge(name string) error {
	switch name {
	case library.EdgeConnection:
		m.ClearConnection()
		return nil
	}
	return fmt.Errorf("unknown Library unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *LibraryMutation) ResetEdge(name string) error {
	switch name {
	case library.EdgeConnection:
		m.ResetConnection()
		return nil
	}
	return fmt.Errorf("unknown Library edge %s", name)
}

// RuleMutation represents an operation that mutates the Rule nodes in the graph.
type RuleMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int
	created_at          *time.Time
	updated_at          *time.Time
	name                *string
	enabled             *bool
	library_key         *string
	granularity         *rule.Granularity
	criteria            *jsontext.Value
	appendcriteria      jsontext.Value
	clearedFields       map[string]struct{}
	connection          *int
	clearedconnection   bool
	action_steps        map[int]struct{}
	removedaction_steps map[int]struct{}
	clearedaction_steps bool
	done                bool
	oldValue            func(context.Context) (*Rule, error)
	predicates          []predicate.Rule
}

var _ ent.Mutation = (*RuleMutation)(nil)

// ruleOption allows management of the mutation configuration using functional options.
type ruleOption func(*RuleMutation)

// newRuleMutation creates new mutation for the Rule entity.
func newRuleMutation(c config, op Op, opts ...ruleOption) *RuleMutation {
	m := &RuleMutation{
		config:        c,
		op:            op,
		typ:           TypeRule,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRuleID sets the ID field of the mutation.
func withRuleID(id int) ruleOption {
	return func(m *RuleMutation) {
		var (
			err   error
			once  sync.Once
			value *Rule
		)
		m.oldValue = func(ctx context.Context) (*Rule, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Rule.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRule sets the old Rule of the mutation.
func withRule(node *Rule) ruleOption {
	return func(m *RuleMutation) {
		m.oldValue = func(context.Context) (*Rule, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RuleMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RuleMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RuleMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RuleMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Rule.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *RuleMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RuleMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Rule entity.
// If the Rule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RuleMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *RuleMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *RuleMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Rule entity.
// If the Rule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *RuleMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetName sets the "name" field.
func (m *RuleMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *RuleMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Rule entity.
// If the Rule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *RuleMutation) ResetName() {
	m.name = nil
}

// SetEnabled sets the "enabled" field.
func (m *RuleMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *RuleMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the Rule entity.
// If the Rule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *RuleMutation) ResetEnabled() {
	m.enabled = nil
}

// SetConnectionID sets the "connection_id" field.
func (m *RuleMutation) SetConnectionID(i int) {
	m.connection = &i
}

// ConnectionID returns the value of the "connection_id" field in the mutation.
func (m *RuleMutation) ConnectionID() (r int, exists bool) {
	v := m.connection
	if v == nil {
		return
	}
	return *v, true
}

// OldConnectionID returns the old "connection_id" field's value of the Rule entity.
// If the Rule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleMutation) OldConnectionID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldConnectionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldConnectionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldConnectionID: %w", err)
	}
	return oldValue.ConnectionID, nil
}

// ResetConnectionID resets all changes to the "connection_id" field.
func (m *RuleMutation) ResetConnectionID() {
	m.connection = nil
}

// SetLibraryKey sets the "library_key" field.
func (m *RuleMutation) SetLibraryKey(s string) {
	m.library_key = &s
}

// LibraryKey returns the value of the "library_key" field in the mutation.
func (m *RuleMutation) LibraryKey() (r string, exists bool) {
	v := m.library_key
	if v == nil {
		return
	}
	return *v, true
}

// OldLibraryKey returns the old "library_key" field's value of the Rule entity.
// If the Rule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleMutation) OldLibraryKey(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLibraryKey is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLibraryKey requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLibraryKey: %w", err)
	}
	return oldValue.LibraryKey, nil
}

// ResetLibraryKey resets all changes to the "library_key" field.
func (m *RuleMutation) ResetLibraryKey() {
	m.library_key = nil
}

// SetGranularity sets the "granularity" field.
func (m *RuleMutation) SetGranularity(r rule.Granularity) {
	m.granularity = &r
}

// Granularity returns the value of the "granularity" field in the mutation.
func (m *RuleMutation) Granularity() (r rule.Granularity, exists bool) {
	v := m.granularity
	if v == nil {
		return
	}
	return *v, true
}

// OldGranularity returns the old "granularity" field's value of the Rule entity.
// If the Rule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleMutation) OldGranularity(ctx context.Context) (v *rule.Granularity, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGranularity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGranularity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGranularity: %w", err)
	}
	return oldValue.Granularity, nil
}

// ClearGranularity clears the value of the "granularity" field.
func (m *RuleMutation) ClearGranularity() {
	m.granularity = nil
	m.clearedFields[rule.FieldGranularity] = struct{}{}
}

// GranularityCleared returns if the "granularity" field was cleared in this mutation.
func (m *RuleMutation) GranularityCleared() bool {
	_, ok := m.clearedFields[rule.FieldGranularity]
	return ok
}

// ResetGranularity resets all changes to the "granularity" field.
func (m *RuleMutation) ResetGranularity() {
	m.granularity = nil
	delete(m.clearedFields, rule.FieldGranularity)
}

// SetCriteria sets the "criteria" field.
func (m *RuleMutation) SetCriteria(j jsontext.Value) {
	m.criteria = &j
	m.appendcriteria = nil
}

// Criteria returns the value of the "criteria" field in the mutation.
func (m *RuleMutation) Criteria() (r jsontext.Value, exists bool) {
	v := m.criteria
	if v == nil {
		return
	}
	return *v, true
}

// OldCriteria returns the old "criteria" field's value of the Rule entity.
// If the Rule object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleMutation) OldCriteria(ctx context.Context) (v jsontext.Value, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCriteria is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCriteria requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCriteria: %w", err)
	}
	return oldValue.Criteria, nil
}

// AppendCriteria adds j to the "criteria" field.
func (m *RuleMutation) AppendCriteria(j jsontext.Value) {
	m.appendcriteria = append(m.appendcriteria, j...)
}

// AppendedCriteria returns the list of values that were appended to the "criteria" field in this mutation.
func (m *RuleMutation) AppendedCriteria() (jsontext.Value, bool) {
	if len(m.appendcriteria) == 0 {
		return nil, false
	}
	return m.appendcriteria, true
}

// ClearCriteria clears the value of the "criteria" field.
func (m *RuleMutation) ClearCriteria() {
	m.criteria = nil
	m.appendcriteria = nil
	m.clearedFields[rule.FieldCriteria] = struct{}{}
}

// CriteriaCleared returns if the "criteria" field was cleared in this mutation.
func (m *RuleMutation) CriteriaCleared() bool {
	_, ok := m.clearedFields[rule.FieldCriteria]
	return ok
}

// ResetCriteria resets all changes to the "criteria" field.
func (m *RuleMutation) ResetCriteria() {
	m.criteria = nil
	m.appendcriteria = nil
	delete(m.clearedFields, rule.FieldCriteria)
}

// ClearConnection clears the "connection" edge to the Connection entity.
func (m *RuleMutation) ClearConnection() {
	m.clearedconnection = true
	m.clearedFields[rule.FieldConnectionID] = struct{}{}
}

// ConnectionCleared reports if the "connection" edge to the Connection entity was cleared.
func (m *RuleMutation) ConnectionCleared() bool {
	return m.clearedconnection
}

// ConnectionIDs returns the "connection" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// ConnectionID instead. It exists only for internal usage by the builders.
func (m *RuleMutation) ConnectionIDs() (ids []int) {
	if id := m.connection; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetConnection resets all changes to the "connection" edge.
func (m *RuleMutation) ResetConnection() {
	m.connection = nil
	m.clearedconnection = false
}

// AddActionStepIDs adds the "action_steps" edge to the RuleActionStep entity by ids.
func (m *RuleMutation) AddActionStepIDs(ids ...int) {
	if m.action_steps == nil {
		m.action_steps = make(map[int]struct{})
	}
	for i := range ids {
		m.action_steps[ids[i]] = struct{}{}
	}
}

// ClearActionSteps clears the "action_steps" edge to the RuleActionStep entity.
func (m *RuleMutation) ClearActionSteps() {
	m.clearedaction_steps = true
}

// ActionStepsCleared reports if the "action_steps" edge to the RuleActionStep entity was cleared.
func (m *RuleMutation) ActionStepsCleared() bool {
	return m.clearedaction_steps
}

// RemoveActionStepIDs removes the "action_steps" edge to the RuleActionStep entity by IDs.
func (m *RuleMutation) RemoveActionStepIDs(ids ...int) {
	if m.removedaction_steps == nil {
		m.removedaction_steps = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.action_steps, ids[i])
		m.removedaction_steps[ids[i]] = struct{}{}
	}
}

// RemovedActionSteps returns the removed IDs of the "action_steps" edge to the RuleActionStep entity.
func (m *RuleMutation) RemovedActionStepsIDs() (ids []int) {
	for id := range m.removedaction_steps {
		ids = append(ids, id)
	}
	return
}

// ActionStepsIDs returns the "action_steps" edge IDs in the mutation.
func (m *RuleMutation) ActionStepsIDs() (ids []int) {
	for id := range m.action_steps {
		ids = append(ids, id)
	}
	return
}

// ResetActionSteps resets all changes to the "action_steps" edge.
func (m *RuleMutation) ResetActionSteps() {
	m.action_steps = nil
	m.clearedaction_steps = false
	m.removedaction_steps = nil
}

// Where appends a list predicates to the RuleMutation builder.
func (m *RuleMutation) Where(ps ...predicate.Rule) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RuleMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RuleMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Rule, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RuleMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RuleMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Rule).
func (m *RuleMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RuleMutation) Fields() []string {
	fields := make([]string, 0, 8)
	if m.created_at != nil {
		fields = append(fields, rule.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, rule.FieldUpdatedAt)
	}
	if m.name != nil {
		fields = append(fields, rule.FieldName)
	}
	if m.enabled != nil {
		fields = append(fields, rule.FieldEnabled)
	}
	if m.connection != nil {
		fields = append(fields, rule.FieldConnectionID)
	}
	if m.library_key != nil {
		fields = append(fields, rule.FieldLibraryKey)
	}
	if m.granularity != nil {
		fields = append(fields, rule.FieldGranularity)
	}
	if m.criteria != nil {
		fields = append(fields, rule.FieldCriteria)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RuleMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case rule.FieldCreatedAt:
		return m.CreatedAt()
	case rule.FieldUpdatedAt:
		return m.UpdatedAt()
	case rule.FieldName:
		return m.Name()
	case rule.FieldEnabled:
		return m.Enabled()
	case rule.FieldConnectionID:
		return m.ConnectionID()
	case rule.FieldLibraryKey:
		return m.LibraryKey()
	case rule.FieldGranularity:
		return m.Granularity()
	case rule.FieldCriteria:
		return m.Criteria()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RuleMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case rule.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case rule.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case rule.FieldName:
		return m.OldName(ctx)
	case rule.FieldEnabled:
		return m.OldEnabled(ctx)
	case rule.FieldConnectionID:
		return m.OldConnectionID(ctx)
	case rule.FieldLibraryKey:
		return m.OldLibraryKey(ctx)
	case rule.FieldGranularity:
		return m.OldGranularity(ctx)
	case rule.FieldCriteria:
		return m.OldCriteria(ctx)
	}
	return nil, fmt.Errorf("unknown Rule field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RuleMutation) SetField(name string, value ent.Value) error {
	switch name {
	case rule.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case rule.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case rule.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case rule.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	case rule.FieldConnectionID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetConnectionID(v)
		return nil
	case rule.FieldLibraryKey:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLibraryKey(v)
		return nil
	case rule.FieldGranularity:
		v, ok := value.(rule.Granularity)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGranularity(v)
		return nil
	case rule.FieldCriteria:
		v, ok := value.(jsontext.Value)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCriteria(v)
		return nil
	}
	return fmt.Errorf("unknown Rule field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RuleMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RuleMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RuleMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Rule numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RuleMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(rule.FieldGranularity) {
		fields = append(fields, rule.FieldGranularity)
	}
	if m.FieldCleared(rule.FieldCriteria) {
		fields = append(fields, rule.FieldCriteria)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RuleMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RuleMutation) ClearField(name string) error {
	switch name {
	case rule.FieldGranularity:
		m.ClearGranularity()
		return nil
	case rule.FieldCriteria:
		m.ClearCriteria()
		return nil
	}
	return fmt.Errorf("unknown Rule nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RuleMutation) ResetField(name string) error {
	switch name {
	case rule.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case rule.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case rule.FieldName:
		m.ResetName()
		return nil
	case rule.FieldEnabled:
		m.ResetEnabled()
		return nil
	case rule.FieldConnectionID:
		m.ResetConnectionID()
		return nil
	case rule.FieldLibraryKey:
		m.ResetLibraryKey()
		return nil
	case rule.FieldGranularity:
		m.ResetGranularity()
		return nil
	case rule.FieldCriteria:
		m.ResetCriteria()
		return nil
	}
	return fmt.Errorf("unknown Rule field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RuleMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.connection != nil {
		edges = append(edges, rule.EdgeConnection)
	}
	if m.action_steps != nil {
		edges = append(edges, rule.EdgeActionSteps)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RuleMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case rule.EdgeConnection:
		if id := m.connection; id != nil {
			return []ent.Value{*id}
		}
	case rule.EdgeActionSteps:
		ids := make([]ent.Value, 0, len(m.action_steps))
		for id := range m.action_steps {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RuleMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedaction_steps != nil {
		edges = append(edges, rule.EdgeActionSteps)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RuleMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case rule.EdgeActionSteps:
		ids := make([]ent.Value, 0, len(m.removedaction_steps))
		for id := range m.removedaction_steps {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RuleMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedconnection {
		edges = append(edges, rule.EdgeConnection)
	}
	if m.clearedaction_steps {
		edges = append(edges, rule.EdgeActionSteps)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RuleMutation) EdgeCleared(name string) bool {
	switch name {
	case rule.EdgeConnection:
		return m.clearedconnection
	case rule.EdgeActionSteps:
		return m.clearedaction_steps
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RuleMutation) ClearEdge(name string) error {
	switch name {
	case rule.EdgeConnection:
		m.ClearConnection()
		return nil
	}
	return fmt.Errorf("unknown Rule unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RuleMutation) ResetEdge(name string) error {
	switch name {
	case rule.EdgeConnection:
		m.ResetConnection()
		return nil
	case rule.EdgeActionSteps:
		m.ResetActionSteps()
		return nil
	}
	return fmt.Errorf("unknown Rule edge %s", name)
}

// RuleActionStepMutation represents an operation that mutates the RuleActionStep nodes in the graph.
type RuleActionStepMutation struct {
	config
	op              Op
	typ             string
	id              *int
	created_at      *time.Time
	updated_at      *time.Time
	position        *int
	addposition     *int
	delay_amount    *int
	adddelay_amount *int
	delay_unit      *ruleactionstep.DelayUnit
	action          *ruleactionstep.Action
	clearedFields   map[string]struct{}
	rule            *int
	clearedrule     bool
	done            bool
	oldValue        func(context.Context) (*RuleActionStep, error)
	predicates      []predicate.RuleActionStep
}

var _ ent.Mutation = (*RuleActionStepMutation)(nil)

// ruleactionstepOption allows management of the mutation configuration using functional options.
type ruleactionstepOption func(*RuleActionStepMutation)

// newRuleActionStepMutation creates new mutation for the RuleActionStep entity.
func newRuleActionStepMutation(c config, op Op, opts ...ruleactionstepOption) *RuleActionStepMutation {
	m := &RuleActionStepMutation{
		config:        c,
		op:            op,
		typ:           TypeRuleActionStep,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withRuleActionStepID sets the ID field of the mutation.
func withRuleActionStepID(id int) ruleactionstepOption {
	return func(m *RuleActionStepMutation) {
		var (
			err   error
			once  sync.Once
			value *RuleActionStep
		)
		m.oldValue = func(ctx context.Context) (*RuleActionStep, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().RuleActionStep.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withRuleActionStep sets the old RuleActionStep of the mutation.
func withRuleActionStep(node *RuleActionStep) ruleactionstepOption {
	return func(m *RuleActionStepMutation) {
		m.oldValue = func(context.Context) (*RuleActionStep, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m RuleActionStepMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m RuleActionStepMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *RuleActionStepMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *RuleActionStepMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().RuleActionStep.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *RuleActionStepMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *RuleActionStepMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the RuleActionStep entity.
// If the RuleActionStep object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleActionStepMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *RuleActionStepMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *RuleActionStepMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *RuleActionStepMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the RuleActionStep entity.
// If the RuleActionStep object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleActionStepMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *RuleActionStepMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetPosition sets the "position" field.
func (m *RuleActionStepMutation) SetPosition(i int) {
	m.position = &i
	m.addposition = nil
}

// Position returns the value of the "position" field in the mutation.
func (m *RuleActionStepMutation) Position() (r int, exists bool) {
	v := m.position
	if v == nil {
		return
	}
	return *v, true
}

// OldPosition returns the old "position" field's value of the RuleActionStep entity.
// If the RuleActionStep object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleActionStepMutation) OldPosition(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPosition is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPosition requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPosition: %w", err)
	}
	return oldValue.Position, nil
}

// AddPosition adds i to the "position" field.
func (m *RuleActionStepMutation) AddPosition(i int) {
	if m.addposition != nil {
		*m.addposition += i
	} else {
		m.addposition = &i
	}
}

// AddedPosition returns the value that was added to the "position" field in this mutation.
func (m *RuleActionStepMutation) AddedPosition() (r int, exists bool) {
	v := m.addposition
	if v == nil {
		return
	}
	return *v, true
}

// ResetPosition resets all changes to the "position" field.
func (m *RuleActionStepMutation) ResetPosition() {
	m.position = nil
	m.addposition = nil
}

// SetDelayAmount sets the "delay_amount" field.
func (m *RuleActionStepMutation) SetDelayAmount(i int) {
	m.delay_amount = &i
	m.adddelay_amount = nil
}

// DelayAmount returns the value of the "delay_amount" field in the mutation.
func (m *RuleActionStepMutation) DelayAmount() (r int, exists bool) {
	v := m.delay_amount
	if v == nil {
		return
	}
	return *v, true
}

// OldDelayAmount returns the old "delay_amount" field's value of the RuleActionStep entity.
// If the RuleActionStep object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleActionStepMutation) OldDelayAmount(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDelayAmount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDelayAmount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDelayAmount: %w", err)
	}
	return oldValue.DelayAmount, nil
}

// AddDelayAmount adds i to the "delay_amount" field.
func (m *RuleActionStepMutation) AddDelayAmount(i int) {
	if m.adddelay_amount != nil {
		*m.adddelay_amount += i
	} else {
		m.adddelay_amount = &i
	}
}

// AddedDelayAmount returns the value that was added to the "delay_amount" field in this mutation.
func (m *RuleActionStepMutation) AddedDelayAmount() (r int, exists bool) {
	v := m.adddelay_amount
	if v == nil {
		return
	}
	return *v, true
}

// ResetDelayAmount resets all changes to the "delay_amount" field.
func (m *RuleActionStepMutation) ResetDelayAmount() {
	m.delay_amount = nil
	m.adddelay_amount = nil
}

// SetDelayUnit sets the "delay_unit" field.
func (m *RuleActionStepMutation) SetDelayUnit(ru ruleactionstep.DelayUnit) {
	m.delay_unit = &ru
}

// DelayUnit returns the value of the "delay_unit" field in the mutation.
func (m *RuleActionStepMutation) DelayUnit() (r ruleactionstep.DelayUnit, exists bool) {
	v := m.delay_unit
	if v == nil {
		return
	}
	return *v, true
}

// OldDelayUnit returns the old "delay_unit" field's value of the RuleActionStep entity.
// If the RuleActionStep object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleActionStepMutation) OldDelayUnit(ctx context.Context) (v ruleactionstep.DelayUnit, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDelayUnit is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDelayUnit requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDelayUnit: %w", err)
	}
	return oldValue.DelayUnit, nil
}

// ResetDelayUnit resets all changes to the "delay_unit" field.
func (m *RuleActionStepMutation) ResetDelayUnit() {
	m.delay_unit = nil
}

// SetAction sets the "action" field.
func (m *RuleActionStepMutation) SetAction(r ruleactionstep.Action) {
	m.action = &r
}

// Action returns the value of the "action" field in the mutation.
func (m *RuleActionStepMutation) Action() (r ruleactionstep.Action, exists bool) {
	v := m.action
	if v == nil {
		return
	}
	return *v, true
}

// OldAction returns the old "action" field's value of the RuleActionStep entity.
// If the RuleActionStep object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleActionStepMutation) OldAction(ctx context.Context) (v ruleactionstep.Action, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAction is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAction requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAction: %w", err)
	}
	return oldValue.Action, nil
}

// ResetAction resets all changes to the "action" field.
func (m *RuleActionStepMutation) ResetAction() {
	m.action = nil
}

// SetRuleID sets the "rule_id" field.
func (m *RuleActionStepMutation) SetRuleID(i int) {
	m.rule = &i
}

// RuleID returns the value of the "rule_id" field in the mutation.
func (m *RuleActionStepMutation) RuleID() (r int, exists bool) {
	v := m.rule
	if v == nil {
		return
	}
	return *v, true
}

// OldRuleID returns the old "rule_id" field's value of the RuleActionStep entity.
// If the RuleActionStep object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *RuleActionStepMutation) OldRuleID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRuleID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRuleID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRuleID: %w", err)
	}
	return oldValue.RuleID, nil
}

// ResetRuleID resets all changes to the "rule_id" field.
func (m *RuleActionStepMutation) ResetRuleID() {
	m.rule = nil
}

// ClearRule clears the "rule" edge to the Rule entity.
func (m *RuleActionStepMutation) ClearRule() {
	m.clearedrule = true
	m.clearedFields[ruleactionstep.FieldRuleID] = struct{}{}
}

// RuleCleared reports if the "rule" edge to the Rule entity was cleared.
func (m *RuleActionStepMutation) RuleCleared() bool {
	return m.clearedrule
}

// RuleIDs returns the "rule" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// RuleID instead. It exists only for internal usage by the builders.
func (m *RuleActionStepMutation) RuleIDs() (ids []int) {
	if id := m.rule; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetRule resets all changes to the "rule" edge.
func (m *RuleActionStepMutation) ResetRule() {
	m.rule = nil
	m.clearedrule = false
}

// Where appends a list predicates to the RuleActionStepMutation builder.
func (m *RuleActionStepMutation) Where(ps ...predicate.RuleActionStep) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the RuleActionStepMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *RuleActionStepMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.RuleActionStep, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *RuleActionStepMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *RuleActionStepMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (RuleActionStep).
func (m *RuleActionStepMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *RuleActionStepMutation) Fields() []string {
	fields := make([]string, 0, 7)
	if m.created_at != nil {
		fields = append(fields, ruleactionstep.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, ruleactionstep.FieldUpdatedAt)
	}
	if m.position != nil {
		fields = append(fields, ruleactionstep.FieldPosition)
	}
	if m.delay_amount != nil {
		fields = append(fields, ruleactionstep.FieldDelayAmount)
	}
	if m.delay_unit != nil {
		fields = append(fields, ruleactionstep.FieldDelayUnit)
	}
	if m.action != nil {
		fields = append(fields, ruleactionstep.FieldAction)
	}
	if m.rule != nil {
		fields = append(fields, ruleactionstep.FieldRuleID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *RuleActionStepMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case ruleactionstep.FieldCreatedAt:
		return m.CreatedAt()
	case ruleactionstep.FieldUpdatedAt:
		return m.UpdatedAt()
	case ruleactionstep.FieldPosition:
		return m.Position()
	case ruleactionstep.FieldDelayAmount:
		return m.DelayAmount()
	case ruleactionstep.FieldDelayUnit:
		return m.DelayUnit()
	case ruleactionstep.FieldAction:
		return m.Action()
	case ruleactionstep.FieldRuleID:
		return m.RuleID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *RuleActionStepMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case ruleactionstep.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case ruleactionstep.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case ruleactionstep.FieldPosition:
		return m.OldPosition(ctx)
	case ruleactionstep.FieldDelayAmount:
		return m.OldDelayAmount(ctx)
	case ruleactionstep.FieldDelayUnit:
		return m.OldDelayUnit(ctx)
	case ruleactionstep.FieldAction:
		return m.OldAction(ctx)
	case ruleactionstep.FieldRuleID:
		return m.OldRuleID(ctx)
	}
	return nil, fmt.Errorf("unknown RuleActionStep field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RuleActionStepMutation) SetField(name string, value ent.Value) error {
	switch name {
	case ruleactionstep.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case ruleactionstep.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case ruleactionstep.FieldPosition:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPosition(v)
		return nil
	case ruleactionstep.FieldDelayAmount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDelayAmount(v)
		return nil
	case ruleactionstep.FieldDelayUnit:
		v, ok := value.(ruleactionstep.DelayUnit)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDelayUnit(v)
		return nil
	case ruleactionstep.FieldAction:
		v, ok := value.(ruleactionstep.Action)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAction(v)
		return nil
	case ruleactionstep.FieldRuleID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRuleID(v)
		return nil
	}
	return fmt.Errorf("unknown RuleActionStep field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *RuleActionStepMutation) AddedFields() []string {
	var fields []string
	if m.addposition != nil {
		fields = append(fields, ruleactionstep.FieldPosition)
	}
	if m.adddelay_amount != nil {
		fields = append(fields, ruleactionstep.FieldDelayAmount)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *RuleActionStepMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case ruleactionstep.FieldPosition:
		return m.AddedPosition()
	case ruleactionstep.FieldDelayAmount:
		return m.AddedDelayAmount()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *RuleActionStepMutation) AddField(name string, value ent.Value) error {
	switch name {
	case ruleactionstep.FieldPosition:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPosition(v)
		return nil
	case ruleactionstep.FieldDelayAmount:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDelayAmount(v)
		return nil
	}
	return fmt.Errorf("unknown RuleActionStep numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *RuleActionStepMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *RuleActionStepMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *RuleActionStepMutation) ClearField(name string) error {
	return fmt.Errorf("unknown RuleActionStep nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *RuleActionStepMutation) ResetField(name string) error {
	switch name {
	case ruleactionstep.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case ruleactionstep.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case ruleactionstep.FieldPosition:
		m.ResetPosition()
		return nil
	case ruleactionstep.FieldDelayAmount:
		m.ResetDelayAmount()
		return nil
	case ruleactionstep.FieldDelayUnit:
		m.ResetDelayUnit()
		return nil
	case ruleactionstep.FieldAction:
		m.ResetAction()
		return nil
	case ruleactionstep.FieldRuleID:
		m.ResetRuleID()
		return nil
	}
	return fmt.Errorf("unknown RuleActionStep field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *RuleActionStepMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.rule != nil {
		edges = append(edges, ruleactionstep.EdgeRule)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *RuleActionStepMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case ruleactionstep.EdgeRule:
		if id := m.rule; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *RuleActionStepMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *RuleActionStepMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *RuleActionStepMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedrule {
		edges = append(edges, ruleactionstep.EdgeRule)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *RuleActionStepMutation) EdgeCleared(name string) bool {
	switch name {
	case ruleactionstep.EdgeRule:
		return m.clearedrule
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *RuleActionStepMutation) ClearEdge(name string) error {
	switch name {
	case ruleactionstep.EdgeRule:
		m.ClearRule()
		return nil
	}
	return fmt.Errorf("unknown RuleActionStep unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *RuleActionStepMutation) ResetEdge(name string) error {
	switch name {
	case ruleactionstep.EdgeRule:
		m.ResetRule()
		return nil
	}
	return fmt.Errorf("unknown RuleActionStep edge %s", name)
}
