// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oom-killed/lib-managerr/ent/rule"
	"github.com/oom-killed/lib-managerr/ent/ruleactionstep"
)

// RuleActionStepCreate is the builder for creating a RuleActionStep entity.
type RuleActionStepCreate struct {
	config
	mutation *RuleActionStepMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RuleActionStepCreate) SetCreatedAt(v time.Time) *RuleActionStepCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RuleActionStepCreate) SetNillableCreatedAt(v *time.Time) *RuleActionStepCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RuleActionStepCreate) SetUpdatedAt(v time.Time) *RuleActionStepCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RuleActionStepCreate) SetNillableUpdatedAt(v *time.Time) *RuleActionStepCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *RuleActionStepCreate) SetPosition(v int) *RuleActionStepCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetDelayAmount sets the "delay_amount" field.
func (_c *RuleActionStepCreate) SetDelayAmount(v int) *RuleActionStepCreate {
	_c.mutation.SetDelayAmount(v)
	return _c
}

// SetDelayUnit sets the "delay_unit" field.
func (_c *RuleActionStepCreate) SetDelayUnit(v ruleactionstep.DelayUnit) *RuleActionStepCreate {
	_c.mutation.SetDelayUnit(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *RuleActionStepCreate) SetAction(v ruleactionstep.Action) *RuleActionStepCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *RuleActionStepCreate) SetNillableAction(v *ruleactionstep.Action) *RuleActionStepCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetRuleID sets the "rule_id" field.
func (_c *RuleActionStepCreate) SetRuleID(v int) *RuleActionStepCreate {
	_c.mutation.SetRuleID(v)
	return _c
}

// SetRule sets the "rule" edge to the Rule entity.
func (_c *RuleActionStepCreate) SetRule(v *Rule) *RuleActionStepCreate {
	return _c.SetRuleID(v.ID)
}

// Mutation returns the RuleActionStepMutation object of the builder.
func (_c *RuleActionStepCreate) Mutation() *RuleActionStepMutation {
	return _c.mutation
}

// Save creates the RuleActionStep in the database.
func (_c *RuleActionStepCreate) Save(ctx context.Context) (*RuleActionStep, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RuleActionStepCreate) SaveX(ctx context.Context) *RuleActionStep {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuleActionStepCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuleActionStepCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RuleActionStepCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ruleactionstep.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ruleactionstep.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Action(); !ok {
		v := ruleactionstep.DefaultAction
		_c.mutation.SetAction(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RuleActionStepCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RuleActionStep.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RuleActionStep.updated_at"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "RuleActionStep.position"`)}
	}
	if _, ok := _c.mutation.DelayAmount(); !ok {
		return &ValidationError{Name: "delay_amount", err: errors.New(`ent: missing required field "RuleActionStep.delay_amount"`)}
	}
	if v, ok := _c.mutation.DelayAmount(); ok {
		if err := ruleactionstep.DelayAmountValidator(v); err != nil {
			return &ValidationError{Name: "delay_amount", err: fmt.Errorf(`ent: validator failed for field "RuleActionStep.delay_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DelayUnit(); !ok {
		return &ValidationError{Name: "delay_unit", err: errors.New(`ent: missing required field "RuleActionStep.delay_unit"`)}
	}
	if v, ok := _c.mutation.DelayUnit(); ok {
		if err := ruleactionstep.DelayUnitValidator(v); err != nil {
			return &ValidationError{Name: "delay_unit", err: fmt.Errorf(`ent: validator failed for field "RuleActionStep.delay_unit": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "RuleActionStep.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := ruleactionstep.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "RuleActionStep.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RuleID(); !ok {
		return &ValidationError{Name: "rule_id", err: errors.New(`ent: missing required field "RuleActionStep.rule_id"`)}
	}
	if len(_c.mutation.RuleIDs()) == 0 {
		return &ValidationError{Name: "rule", err: errors.New(`ent: missing required edge "RuleActionStep.rule"`)}
	}
	return nil
}

func (_c *RuleActionStepCreate) sqlSave(ctx context.Context) (*RuleActionStep, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RuleActionStepCreate) createSpec() (*RuleActionStep, *sqlgraph.CreateSpec) {
	var (
		_node = &RuleActionStep{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ruleactionstep.Table, sqlgraph.NewFieldSpec(ruleactionstep.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ruleactionstep.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ruleactionstep.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(ruleactionstep.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.DelayAmount(); ok {
		_spec.SetField(ruleactionstep.FieldDelayAmount, field.TypeInt, value)
		_node.DelayAmount = value
	}
	if value, ok := _c.mutation.DelayUnit(); ok {
		_spec.SetField(ruleactionstep.FieldDelayUnit, field.TypeEnum, value)
		_node.DelayUnit = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(ruleactionstep.FieldAction, field.TypeEnum, value)
		_node.Action = value
	}
	if nodes := _c.mutation.RuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleactionstep.RuleTable,
			Columns: []string{ruleactionstep.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RuleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RuleActionStepCreateBulk is the builder for creating many RuleActionStep entities in bulk.
type RuleActionStepCreateBulk struct {
	config
	err      error
	builders []*RuleActionStepCreate
}

// Save creates the RuleActionStep entities in the database.
func (_c *RuleActionStepCreateBulk) Save(ctx context.Context) ([]*RuleActionStep, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RuleActionStep, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RuleActionStepMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RuleActionStepCreateBulk) SaveX(ctx context.Context) []*RuleActionStep {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RuleActionStepCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RuleActionStepCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
