// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oom-killed/lib-managerr/ent/connection"
	"github.com/oom-killed/lib-managerr/ent/predicate"
	"github.com/oom-killed/lib-managerr/ent/rule"
)

// RuleUpdate is the builder for updating Rule entities.
type RuleUpdate struct {
	config
	hooks    []Hook
	mutation *RuleMutation
}

// Where appends a list predicates to the RuleUpdate builder.
func (_u *RuleUpdate) Where(ps ...predicate.Rule) *RuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuleUpdate) SetUpdatedAt(v time.Time) *RuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RuleUpdate) SetName(v string) *RuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableName(v *string) *RuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RuleUpdate) SetEnabled(v bool) *RuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableEnabled(v *bool) *RuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *RuleUpdate) SetAction(v rule.Action) *RuleUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableAction(v *rule.Action) *RuleUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetConnectionID sets the "connection_id" field.
func (_u *RuleUpdate) SetConnectionID(v int) *RuleUpdate {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableConnectionID(v *int) *RuleUpdate {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetLibraryKey sets the "library_key" field.
func (_u *RuleUpdate) SetLibraryKey(v string) *RuleUpdate {
	_u.mutation.SetLibraryKey(v)
	return _u
}

// SetNillableLibraryKey sets the "library_key" field if the given value is not nil.
func (_u *RuleUpdate) SetNillableLibraryKey(v *string) *RuleUpdate {
	if v != nil {
		_u.SetLibraryKey(*v)
	}
	return _u
}

// SetConnection sets the "connection" edge to the Connection entity.
func (_u *RuleUpdate) SetConnection(v *Connection) *RuleUpdate {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the RuleMutation object of the builder.
func (_u *RuleUpdate) Mutation() *RuleMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the Connection entity.
func (_u *RuleUpdate) ClearConnection() *RuleUpdate {
	_u.mutation.ClearConnection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Rule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := rule.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "Rule.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LibraryKey(); ok {
		if err := rule.LibraryKeyValidator(v); err != nil {
			return &ValidationError{Name: "library_key", err: fmt.Errorf(`ent: validator failed for field "Rule.library_key": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Rule.connection"`)
	}
	return nil
}

func (_u *RuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rule.Table, rule.Columns, sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(rule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(rule.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LibraryKey(); ok {
		_spec.SetField(rule.FieldLibraryKey, field.TypeString, value)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.ConnectionTable,
			Columns: []string{rule.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.ConnectionTable,
			Columns: []string{rule.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RuleUpdateOne is the builder for updating a single Rule entity.
type RuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuleUpdateOne) SetUpdatedAt(v time.Time) *RuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *RuleUpdateOne) SetName(v string) *RuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableName(v *string) *RuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RuleUpdateOne) SetEnabled(v bool) *RuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableEnabled(v *bool) *RuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *RuleUpdateOne) SetAction(v rule.Action) *RuleUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableAction(v *rule.Action) *RuleUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetConnectionID sets the "connection_id" field.
func (_u *RuleUpdateOne) SetConnectionID(v int) *RuleUpdateOne {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableConnectionID(v *int) *RuleUpdateOne {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetLibraryKey sets the "library_key" field.
func (_u *RuleUpdateOne) SetLibraryKey(v string) *RuleUpdateOne {
	_u.mutation.SetLibraryKey(v)
	return _u
}

// SetNillableLibraryKey sets the "library_key" field if the given value is not nil.
func (_u *RuleUpdateOne) SetNillableLibraryKey(v *string) *RuleUpdateOne {
	if v != nil {
		_u.SetLibraryKey(*v)
	}
	return _u
}

// SetConnection sets the "connection" edge to the Connection entity.
func (_u *RuleUpdateOne) SetConnection(v *Connection) *RuleUpdateOne {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the RuleMutation object of the builder.
func (_u *RuleUpdateOne) Mutation() *RuleMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the Connection entity.
func (_u *RuleUpdateOne) ClearConnection() *RuleUpdateOne {
	_u.mutation.ClearConnection()
	return _u
}

// Where appends a list predicates to the RuleUpdate builder.
func (_u *RuleUpdateOne) Where(ps ...predicate.Rule) *RuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RuleUpdateOne) Select(field string, fields ...string) *RuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Rule entity.
func (_u *RuleUpdateOne) Save(ctx context.Context) (*Rule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleUpdateOne) SaveX(ctx context.Context) *Rule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Rule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := rule.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "Rule.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LibraryKey(); ok {
		if err := rule.LibraryKeyValidator(v); err != nil {
			return &ValidationError{Name: "library_key", err: fmt.Errorf(`ent: validator failed for field "Rule.library_key": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Rule.connection"`)
	}
	return nil
}

func (_u *RuleUpdateOne) sqlSave(ctx context.Context) (_node *Rule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rule.Table, rule.Columns, sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Rule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rule.FieldID)
		for _, f := range fields {
			if !rule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(rule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(rule.FieldAction, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.LibraryKey(); ok {
		_spec.SetField(rule.FieldLibraryKey, field.TypeString, value)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.ConnectionTable,
			Columns: []string{rule.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rule.ConnectionTable,
			Columns: []string{rule.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(connection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Rule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
