// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/oom-killed/lib-managerr/ent/rule"
	"github.com/oom-killed/lib-managerr/ent/ruleactionstep"
)

// RuleActionStep is the model entity for the RuleActionStep schema.
type RuleActionStep struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// DelayAmount holds the value of the "delay_amount" field.
	DelayAmount int `json:"delayAmount,omitempty"`
	// DelayUnit holds the value of the "delay_unit" field.
	DelayUnit ruleactionstep.DelayUnit `json:"delayUnit,omitempty"`
	// Action holds the value of the "action" field.
	Action ruleactionstep.Action `json:"action,omitempty"`
	// RuleID holds the value of the "rule_id" field.
	RuleID int `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RuleActionStepQuery when eager-loading is set.
	Edges        RuleActionStepEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RuleActionStepEdges holds the relations/edges for other nodes in the graph.
type RuleActionStepEdges struct {
	// Rule holds the value of the rule edge.
	Rule *Rule `json:"rule,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RuleOrErr returns the Rule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RuleActionStepEdges) RuleOrErr() (*Rule, error) {
	if e.Rule != nil {
		return e.Rule, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: rule.Label}
	}
	return nil, &NotLoadedError{edge: "rule"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RuleActionStep) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ruleactionstep.FieldID, ruleactionstep.FieldPosition, ruleactionstep.FieldDelayAmount, ruleactionstep.FieldRuleID:
			values[i] = new(sql.NullInt64)
		case ruleactionstep.FieldDelayUnit, ruleactionstep.FieldAction:
			values[i] = new(sql.NullString)
		case ruleactionstep.FieldCreatedAt, ruleactionstep.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RuleActionStep fields.
func (_m *RuleActionStep) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ruleactionstep.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ruleactionstep.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ruleactionstep.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ruleactionstep.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case ruleactionstep.FieldDelayAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delay_amount", values[i])
			} else if value.Valid {
				_m.DelayAmount = int(value.Int64)
			}
		case ruleactionstep.FieldDelayUnit:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delay_unit", values[i])
			} else if value.Valid {
				_m.DelayUnit = ruleactionstep.DelayUnit(value.String)
			}
		case ruleactionstep.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = ruleactionstep.Action(value.String)
			}
		case ruleactionstep.FieldRuleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RuleActionStep.
// This includes values selected through modifiers, order, etc.
func (_m *RuleActionStep) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRule queries the "rule" edge of the RuleActionStep entity.
func (_m *RuleActionStep) QueryRule() *RuleQuery {
	return NewRuleActionStepClient(_m.config).QueryRule(_m)
}

// Update returns a builder for updating this RuleActionStep.
// Note that you need to call RuleActionStep.Unwrap() before calling this method if this RuleActionStep
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RuleActionStep) Update() *RuleActionStepUpdateOne {
	return NewRuleActionStepClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RuleActionStep entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RuleActionStep) Unwrap() *RuleActionStep {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RuleActionStep is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RuleActionStep) String() string {
	var builder strings.Builder
	builder.WriteString("RuleActionStep(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("delay_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.DelayAmount))
	builder.WriteString(", ")
	builder.WriteString("delay_unit=")
	builder.WriteString(fmt.Sprintf("%v", _m.DelayUnit))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", _m.Action))
	builder.WriteString(", ")
	builder.WriteString("rule_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RuleID))
	builder.WriteByte(')')
	return builder.String()
}

// RuleActionSteps is a parsable slice of RuleActionStep.
type RuleActionSteps []*RuleActionStep
