// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oom-killed/lib-managerr/ent/predicate"
	"github.com/oom-killed/lib-managerr/ent/ruleactionstep"
)

// RuleActionStepDelete is the builder for deleting a RuleActionStep entity.
type RuleActionStepDelete struct {
	config
	hooks    []Hook
	mutation *RuleActionStepMutation
}

// Where appends a list predicates to the RuleActionStepDelete builder.
func (_d *RuleActionStepDelete) Where(ps ...predicate.RuleActionStep) *RuleActionStepDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RuleActionStepDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RuleActionStepDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RuleActionStepDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ruleactionstep.Table, sqlgraph.NewFieldSpec(ruleactionstep.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RuleActionStepDeleteOne is the builder for deleting a single RuleActionStep entity.
type RuleActionStepDeleteOne struct {
	_d *RuleActionStepDelete
}

// Where appends a list predicates to the RuleActionStepDelete builder.
func (_d *RuleActionStepDeleteOne) Where(ps ...predicate.RuleActionStep) *RuleActionStepDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RuleActionStepDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ruleactionstep.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RuleActionStepDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
