// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/oom-killed/lib-managerr/ent/predicate"
	"github.com/oom-killed/lib-managerr/ent/rule"
	"github.com/oom-killed/lib-managerr/ent/ruleactionstep"
)

// RuleActionStepUpdate is the builder for updating RuleActionStep entities.
type RuleActionStepUpdate struct {
	config
	hooks    []Hook
	mutation *RuleActionStepMutation
}

// Where appends a list predicates to the RuleActionStepUpdate builder.
func (_u *RuleActionStepUpdate) Where(ps ...predicate.RuleActionStep) *RuleActionStepUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuleActionStepUpdate) SetUpdatedAt(v time.Time) *RuleActionStepUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPosition sets the "position" field.
func (_u *RuleActionStepUpdate) SetPosition(v int) *RuleActionStepUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *RuleActionStepUpdate) SetNillablePosition(v *int) *RuleActionStepUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *RuleActionStepUpdate) AddPosition(v int) *RuleActionStepUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetDelayAmount sets the "delay_amount" field.
func (_u *RuleActionStepUpdate) SetDelayAmount(v int) *RuleActionStepUpdate {
	_u.mutation.ResetDelayAmount()
	_u.mutation.SetDelayAmount(v)
	return _u
}

// SetNillableDelayAmount sets the "delay_amount" field if the given value is not nil.
func (_u *RuleActionStepUpdate) SetNillableDelayAmount(v *int) *RuleActionStepUpdate {
	if v != nil {
		_u.SetDelayAmount(*v)
	}
	return _u
}

// AddDelayAmount adds value to the "delay_amount" field.
func (_u *RuleActionStepUpdate) AddDelayAmount(v int) *RuleActionStepUpdate {
	_u.mutation.AddDelayAmount(v)
	return _u
}

// SetDelayUnit sets the "delay_unit" field.
func (_u *RuleActionStepUpdate) SetDelayUnit(v ruleactionstep.DelayUnit) *RuleActionStepUpdate {
	_u.mutation.SetDelayUnit(v)
	return _u
}

// SetNillableDelayUnit sets the "delay_unit" field if the given value is not nil.
func (_u *RuleActionStepUpdate) SetNillableDelayUnit(v *ruleactionstep.DelayUnit) *RuleActionStepUpdate {
	if v != nil {
		_u.SetDelayUnit(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *RuleActionStepUpdate) SetAction(v ruleactionstep.Action) *RuleActionStepUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RuleActionStepUpdate) SetNillableAction(v *ruleactionstep.Action) *RuleActionStepUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *RuleActionStepUpdate) SetRuleID(v int) *RuleActionStepUpdate {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *RuleActionStepUpdate) SetNillableRuleID(v *int) *RuleActionStepUpdate {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetRule sets the "rule" edge to the Rule entity.
func (_u *RuleActionStepUpdate) SetRule(v *Rule) *RuleActionStepUpdate {
	return _u.SetRuleID(v.ID)
}

// Mutation returns the RuleActionStepMutation object of the builder.
func (_u *RuleActionStepUpdate) Mutation() *RuleActionStepMutation {
	return _u.mutation
}

// ClearRule clears the "rule" edge to the Rule entity.
func (_u *RuleActionStepUpdate) ClearRule() *RuleActionStepUpdate {
	_u.mutation.ClearRule()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RuleActionStepUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleActionStepUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RuleActionStepUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleActionStepUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuleActionStepUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ruleactionstep.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleActionStepUpdate) check() error {
	if v, ok := _u.mutation.DelayAmount(); ok {
		if err := ruleactionstep.DelayAmountValidator(v); err != nil {
			return &ValidationError{Name: "delay_amount", err: fmt.Errorf(`ent: validator failed for field "RuleActionStep.delay_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DelayUnit(); ok {
		if err := ruleactionstep.DelayUnitValidator(v); err != nil {
			return &ValidationError{Name: "delay_unit", err: fmt.Errorf(`ent: validator failed for field "RuleActionStep.delay_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := ruleactionstep.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "RuleActionStep.action": %w`, err)}
		}
	}
	if _u.mutation.RuleCleared() && len(_u.mutation.RuleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RuleActionStep.rule"`)
	}
	return nil
}

func (_u *RuleActionStepUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ruleactionstep.Table, ruleactionstep.Columns, sqlgraph.NewFieldSpec(ruleactionstep.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ruleactionstep.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(ruleactionstep.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(ruleactionstep.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DelayAmount(); ok {
		_spec.SetField(ruleactionstep.FieldDelayAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDelayAmount(); ok {
		_spec.AddField(ruleactionstep.FieldDelayAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DelayUnit(); ok {
		_spec.SetField(ruleactionstep.FieldDelayUnit, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(ruleactionstep.FieldAction, field.TypeEnum, value)
	}
	if _u.mutation.RuleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleactionstep.RuleTable,
			Columns: []string{ruleactionstep.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleactionstep.RuleTable,
			Columns: []string{ruleactionstep.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ruleactionstep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RuleActionStepUpdateOne is the builder for updating a single RuleActionStep entity.
type RuleActionStepUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RuleActionStepMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RuleActionStepUpdateOne) SetUpdatedAt(v time.Time) *RuleActionStepUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPosition sets the "position" field.
func (_u *RuleActionStepUpdateOne) SetPosition(v int) *RuleActionStepUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *RuleActionStepUpdateOne) SetNillablePosition(v *int) *RuleActionStepUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *RuleActionStepUpdateOne) AddPosition(v int) *RuleActionStepUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetDelayAmount sets the "delay_amount" field.
func (_u *RuleActionStepUpdateOne) SetDelayAmount(v int) *RuleActionStepUpdateOne {
	_u.mutation.ResetDelayAmount()
	_u.mutation.SetDelayAmount(v)
	return _u
}

// SetNillableDelayAmount sets the "delay_amount" field if the given value is not nil.
func (_u *RuleActionStepUpdateOne) SetNillableDelayAmount(v *int) *RuleActionStepUpdateOne {
	if v != nil {
		_u.SetDelayAmount(*v)
	}
	return _u
}

// AddDelayAmount adds value to the "delay_amount" field.
func (_u *RuleActionStepUpdateOne) AddDelayAmount(v int) *RuleActionStepUpdateOne {
	_u.mutation.AddDelayAmount(v)
	return _u
}

// SetDelayUnit sets the "delay_unit" field.
func (_u *RuleActionStepUpdateOne) SetDelayUnit(v ruleactionstep.DelayUnit) *RuleActionStepUpdateOne {
	_u.mutation.SetDelayUnit(v)
	return _u
}

// SetNillableDelayUnit sets the "delay_unit" field if the given value is not nil.
func (_u *RuleActionStepUpdateOne) SetNillableDelayUnit(v *ruleactionstep.DelayUnit) *RuleActionStepUpdateOne {
	if v != nil {
		_u.SetDelayUnit(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *RuleActionStepUpdateOne) SetAction(v ruleactionstep.Action) *RuleActionStepUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *RuleActionStepUpdateOne) SetNillableAction(v *ruleactionstep.Action) *RuleActionStepUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *RuleActionStepUpdateOne) SetRuleID(v int) *RuleActionStepUpdateOne {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *RuleActionStepUpdateOne) SetNillableRuleID(v *int) *RuleActionStepUpdateOne {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetRule sets the "rule" edge to the Rule entity.
func (_u *RuleActionStepUpdateOne) SetRule(v *Rule) *RuleActionStepUpdateOne {
	return _u.SetRuleID(v.ID)
}

// Mutation returns the RuleActionStepMutation object of the builder.
func (_u *RuleActionStepUpdateOne) Mutation() *RuleActionStepMutation {
	return _u.mutation
}

// ClearRule clears the "rule" edge to the Rule entity.
func (_u *RuleActionStepUpdateOne) ClearRule() *RuleActionStepUpdateOne {
	_u.mutation.ClearRule()
	return _u
}

// Where appends a list predicates to the RuleActionStepUpdate builder.
func (_u *RuleActionStepUpdateOne) Where(ps ...predicate.RuleActionStep) *RuleActionStepUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RuleActionStepUpdateOne) Select(field string, fields ...string) *RuleActionStepUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RuleActionStep entity.
func (_u *RuleActionStepUpdateOne) Save(ctx context.Context) (*RuleActionStep, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RuleActionStepUpdateOne) SaveX(ctx context.Context) *RuleActionStep {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RuleActionStepUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RuleActionStepUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RuleActionStepUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ruleactionstep.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RuleActionStepUpdateOne) check() error {
	if v, ok := _u.mutation.DelayAmount(); ok {
		if err := ruleactionstep.DelayAmountValidator(v); err != nil {
			return &ValidationError{Name: "delay_amount", err: fmt.Errorf(`ent: validator failed for field "RuleActionStep.delay_amount": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DelayUnit(); ok {
		if err := ruleactionstep.DelayUnitValidator(v); err != nil {
			return &ValidationError{Name: "delay_unit", err: fmt.Errorf(`ent: validator failed for field "RuleActionStep.delay_unit": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := ruleactionstep.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "RuleActionStep.action": %w`, err)}
		}
	}
	if _u.mutation.RuleCleared() && len(_u.mutation.RuleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RuleActionStep.rule"`)
	}
	return nil
}

func (_u *RuleActionStepUpdateOne) sqlSave(ctx context.Context) (_node *RuleActionStep, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ruleactionstep.Table, ruleactionstep.Columns, sqlgraph.NewFieldSpec(ruleactionstep.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RuleActionStep.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ruleactionstep.FieldID)
		for _, f := range fields {
			if !ruleactionstep.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ruleactionstep.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ruleactionstep.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(ruleactionstep.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(ruleactionstep.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DelayAmount(); ok {
		_spec.SetField(ruleactionstep.FieldDelayAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDelayAmount(); ok {
		_spec.AddField(ruleactionstep.FieldDelayAmount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DelayUnit(); ok {
		_spec.SetField(ruleactionstep.FieldDelayUnit, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(ruleactionstep.FieldAction, field.TypeEnum, value)
	}
	if _u.mutation.RuleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleactionstep.RuleTable,
			Columns: []string{ruleactionstep.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RuleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ruleactionstep.RuleTable,
			Columns: []string{ruleactionstep.RuleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RuleActionStep{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ruleactionstep.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
