// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/oom-killed/lib-managerr/ent/connection"
	"github.com/oom-killed/lib-managerr/ent/library"
	"github.com/oom-killed/lib-managerr/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	connectionMixin := schema.Connection{}.Mixin()
	connectionMixinFields0 := connectionMixin[0].Fields()
	_ = connectionMixinFields0
	connectionFields := schema.Connection{}.Fields()
	_ = connectionFields
	// connectionDescCreatedAt is the schema descriptor for created_at field.
	connectionDescCreatedAt := connectionMixinFields0[0].Descriptor()
	// connection.DefaultCreatedAt holds the default value on creation for the created_at field.
	connection.DefaultCreatedAt = connectionDescCreatedAt.Default.(func() time.Time)
	// connectionDescUpdatedAt is the schema descriptor for updated_at field.
	connectionDescUpdatedAt := connectionMixinFields0[1].Descriptor()
	// connection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	connection.DefaultUpdatedAt = connectionDescUpdatedAt.Default.(func() time.Time)
	// connection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	connection.UpdateDefaultUpdatedAt = connectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// connectionDescName is the schema descriptor for name field.
	connectionDescName := connectionFields[1].Descriptor()
	// connection.NameValidator is a validator for the "name" field. It is called by the builders before save.
	connection.NameValidator = connectionDescName.Validators[0].(func(string) error)
	// connectionDescHost is the schema descriptor for host field.
	connectionDescHost := connectionFields[2].Descriptor()
	// connection.HostValidator is a validator for the "host" field. It is called by the builders before save.
	connection.HostValidator = connectionDescHost.Validators[0].(func(string) error)
	// connectionDescPort is the schema descriptor for port field.
	connectionDescPort := connectionFields[3].Descriptor()
	// connection.PortValidator is a validator for the "port" field. It is called by the builders before save.
	connection.PortValidator = connectionDescPort.Validators[0].(func(int) error)
	// connectionDescSsl is the schema descriptor for ssl field.
	connectionDescSsl := connectionFields[4].Descriptor()
	// connection.DefaultSsl holds the default value on creation for the ssl field.
	connection.DefaultSsl = connectionDescSsl.Default.(bool)
	// connectionDescToken is the schema descriptor for token field.
	connectionDescToken := connectionFields[5].Descriptor()
	// connection.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	connection.TokenValidator = connectionDescToken.Validators[0].(func(string) error)
	libraryMixin := schema.Library{}.Mixin()
	libraryMixinFields0 := libraryMixin[0].Fields()
	_ = libraryMixinFields0
	libraryFields := schema.Library{}.Fields()
	_ = libraryFields
	// libraryDescCreatedAt is the schema descriptor for created_at field.
	libraryDescCreatedAt := libraryMixinFields0[0].Descriptor()
	// library.DefaultCreatedAt holds the default value on creation for the created_at field.
	library.DefaultCreatedAt = libraryDescCreatedAt.Default.(func() time.Time)
	// libraryDescUpdatedAt is the schema descriptor for updated_at field.
	libraryDescUpdatedAt := libraryMixinFields0[1].Descriptor()
	// library.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	library.DefaultUpdatedAt = libraryDescUpdatedAt.Default.(func() time.Time)
	// library.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	library.UpdateDefaultUpdatedAt = libraryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// libraryDescExternalID is the schema descriptor for external_id field.
	libraryDescExternalID := libraryFields[0].Descriptor()
	// library.ExternalIDValidator is a validator for the "external_id" field. It is called by the builders before save.
	library.ExternalIDValidator = libraryDescExternalID.Validators[0].(func(string) error)
	// libraryDescTitle is the schema descriptor for title field.
	libraryDescTitle := libraryFields[1].Descriptor()
	// library.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	library.TitleValidator = libraryDescTitle.Validators[0].(func(string) error)
	// libraryDescEnabled is the schema descriptor for enabled field.
	libraryDescEnabled := libraryFields[3].Descriptor()
	// library.DefaultEnabled holds the default value on creation for the enabled field.
	library.DefaultEnabled = libraryDescEnabled.Default.(bool)
}
