// Code generated by ent, DO NOT EDIT.

package ruleactionstep

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ruleactionstep type in the database.
	Label = "rule_action_step"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPosition holds the string denoting the position field in the database.
	FieldPosition = "position"
	// FieldDelayAmount holds the string denoting the delay_amount field in the database.
	FieldDelayAmount = "delay_amount"
	// FieldDelayUnit holds the string denoting the delay_unit field in the database.
	FieldDelayUnit = "delay_unit"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// EdgeRule holds the string denoting the rule edge name in mutations.
	EdgeRule = "rule"
	// Table holds the table name of the ruleactionstep in the database.
	Table = "rule_action_steps"
	// RuleTable is the table that holds the rule relation/edge.
	RuleTable = "rule_action_steps"
	// RuleInverseTable is the table name for the Rule entity.
	// It exists in this package in order to avoid circular dependency with the "rule" package.
	RuleInverseTable = "rules"
	// RuleColumn is the table column denoting the rule relation/edge.
	RuleColumn = "rule_id"
)

// Columns holds all SQL columns for ruleactionstep fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPosition,
	FieldDelayAmount,
	FieldDelayUnit,
	FieldAction,
	FieldRuleID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DelayAmountValidator is a validator for the "delay_amount" field. It is called by the builders before save.
	DelayAmountValidator func(int) error
)

// DelayUnit defines the type for the "delay_unit" enum field.
type DelayUnit string

// DelayUnit values.
const (
	DelayUnitHours  DelayUnit = "hours"
	DelayUnitDays   DelayUnit = "days"
	DelayUnitWeeks  DelayUnit = "weeks"
	DelayUnitMonths DelayUnit = "months"
)

func (du DelayUnit) String() string {
	return string(du)
}

// DelayUnitValidator is a validator for the "delay_unit" field enum values. It is called by the builders before save.
func DelayUnitValidator(du DelayUnit) error {
	switch du {
	case DelayUnitHours, DelayUnitDays, DelayUnitWeeks, DelayUnitMonths:
		return nil
	default:
		return fmt.Errorf("ruleactionstep: invalid enum value for delay_unit field: %q", du)
	}
}

// Action defines the type for the "action" enum field.
type Action string

// ActionDoNothing is the default value of the Action enum.
const DefaultAction = ActionDoNothing

// Action values.
const (
	ActionChangeQualityAndSearch  Action = "change_quality_and_search"
	ActionDelete                  Action = "delete"
	ActionDoNothing               Action = "do_nothing"
	ActionUnmonitorAndDeleteFiles Action = "unmonitor_and_delete_files"
	ActionUnmonitorAndKeepFiles   Action = "unmonitor_and_keep_files"
)

func (a Action) String() string {
	return string(a)
}

// ActionValidator is a validator for the "action" field enum values. It is called by the builders before save.
func ActionValidator(a Action) error {
	switch a {
	case ActionChangeQualityAndSearch, ActionDelete, ActionDoNothing, ActionUnmonitorAndDeleteFiles, ActionUnmonitorAndKeepFiles:
		return nil
	default:
		return fmt.Errorf("ruleactionstep: invalid enum value for action field: %q", a)
	}
}

// OrderOption defines the ordering options for the RuleActionStep queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPosition orders the results by the position field.
func ByPosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPosition, opts...).ToFunc()
}

// ByDelayAmount orders the results by the delay_amount field.
func ByDelayAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelayAmount, opts...).ToFunc()
}

// ByDelayUnit orders the results by the delay_unit field.
func ByDelayUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDelayUnit, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// ByRuleField orders the results by rule field.
func ByRuleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRuleStep(), sql.OrderByField(field, opts...))
	}
}
func newRuleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RuleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RuleTable, RuleColumn),
	)
}
