// Code generated by ent, DO NOT EDIT.

package ruleactionstep

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/oom-killed/lib-managerr/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldUpdatedAt, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldPosition, v))
}

// DelayAmount applies equality check predicate on the "delay_amount" field. It's identical to DelayAmountEQ.
func DelayAmount(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldDelayAmount, v))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldRuleID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLTE(FieldUpdatedAt, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLTE(FieldPosition, v))
}

// DelayAmountEQ applies the EQ predicate on the "delay_amount" field.
func DelayAmountEQ(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldDelayAmount, v))
}

// DelayAmountNEQ applies the NEQ predicate on the "delay_amount" field.
func DelayAmountNEQ(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNEQ(FieldDelayAmount, v))
}

// DelayAmountIn applies the In predicate on the "delay_amount" field.
func DelayAmountIn(vs ...int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldIn(FieldDelayAmount, vs...))
}

// DelayAmountNotIn applies the NotIn predicate on the "delay_amount" field.
func DelayAmountNotIn(vs ...int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNotIn(FieldDelayAmount, vs...))
}

// DelayAmountGT applies the GT predicate on the "delay_amount" field.
func DelayAmountGT(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGT(FieldDelayAmount, v))
}

// DelayAmountGTE applies the GTE predicate on the "delay_amount" field.
func DelayAmountGTE(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldGTE(FieldDelayAmount, v))
}

// DelayAmountLT applies the LT predicate on the "delay_amount" field.
func DelayAmountLT(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLT(FieldDelayAmount, v))
}

// DelayAmountLTE applies the LTE predicate on the "delay_amount" field.
func DelayAmountLTE(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldLTE(FieldDelayAmount, v))
}

// DelayUnitEQ applies the EQ predicate on the "delay_unit" field.
func DelayUnitEQ(v DelayUnit) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldDelayUnit, v))
}

// DelayUnitNEQ applies the NEQ predicate on the "delay_unit" field.
func DelayUnitNEQ(v DelayUnit) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNEQ(FieldDelayUnit, v))
}

// DelayUnitIn applies the In predicate on the "delay_unit" field.
func DelayUnitIn(vs ...DelayUnit) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldIn(FieldDelayUnit, vs...))
}

// DelayUnitNotIn applies the NotIn predicate on the "delay_unit" field.
func DelayUnitNotIn(vs ...DelayUnit) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNotIn(FieldDelayUnit, vs...))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v Action) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v Action) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...Action) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...Action) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNotIn(FieldAction, vs...))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...int) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.FieldNotIn(FieldRuleID, vs...))
}

// HasRule applies the HasEdge predicate on the "rule" edge.
func HasRule() predicate.RuleActionStep {
	return predicate.RuleActionStep(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RuleTable, RuleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRuleWith applies the HasEdge predicate on the "rule" edge with a given conditions (other predicates).
func HasRuleWith(preds ...predicate.Rule) predicate.RuleActionStep {
	return predicate.RuleActionStep(func(s *sql.Selector) {
		step := newRuleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RuleActionStep) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RuleActionStep) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RuleActionStep) predicate.RuleActionStep {
	return predicate.RuleActionStep(sql.NotPredicates(p))
}
