// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConnectionsColumns holds the columns for the "connections" table.
	ConnectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"plex", "radarr", "sonarr", "seerr"}},
		{Name: "name", Type: field.TypeString},
		{Name: "host", Type: field.TypeString},
		{Name: "port", Type: field.TypeInt},
		{Name: "ssl", Type: field.TypeBool, Default: false},
		{Name: "token", Type: field.TypeString},
	}
	// ConnectionsTable holds the schema information for the "connections" table.
	ConnectionsTable = &schema.Table{
		Name:       "connections",
		Columns:    ConnectionsColumns,
		PrimaryKey: []*schema.Column{ConnectionsColumns[0]},
	}
	// LibrariesColumns holds the columns for the "libraries" table.
	LibrariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "external_id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "media_type", Type: field.TypeEnum, Enums: []string{"movie", "show", "artist"}},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "connection_libraries", Type: field.TypeInt},
	}
	// LibrariesTable holds the schema information for the "libraries" table.
	LibrariesTable = &schema.Table{
		Name:       "libraries",
		Columns:    LibrariesColumns,
		PrimaryKey: []*schema.Column{LibrariesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "libraries_connections_libraries",
				Columns:    []*schema.Column{LibrariesColumns[7]},
				RefColumns: []*schema.Column{ConnectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "library_external_id_connection_libraries",
				Unique:  true,
				Columns: []*schema.Column{LibrariesColumns[3], LibrariesColumns[7]},
			},
		},
	}
	// RulesColumns holds the columns for the "rules" table.
	RulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "library_key", Type: field.TypeString},
		{Name: "granularity", Type: field.TypeEnum, Nullable: true, Enums: []string{"show", "season", "episode"}},
		{Name: "connection_id", Type: field.TypeInt},
	}
	// RulesTable holds the schema information for the "rules" table.
	RulesTable = &schema.Table{
		Name:       "rules",
		Columns:    RulesColumns,
		PrimaryKey: []*schema.Column{RulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rules_connections_rules",
				Columns:    []*schema.Column{RulesColumns[7]},
				RefColumns: []*schema.Column{ConnectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// RuleActionStepsColumns holds the columns for the "rule_action_steps" table.
	RuleActionStepsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "position", Type: field.TypeInt},
		{Name: "delay_amount", Type: field.TypeInt},
		{Name: "delay_unit", Type: field.TypeEnum, Enums: []string{"hours", "days", "weeks", "months"}},
		{Name: "action", Type: field.TypeEnum, Enums: []string{"change_quality_and_search", "delete", "do_nothing", "unmonitor_and_delete_files", "unmonitor_and_keep_files", "delete_entire_show", "unmonitor_show_delete_all_episodes", "unmonitor_show_keep_files", "unmonitor_show_delete_existing_episodes", "season_unmonitor_delete_existing_episodes", "season_unmonitor_delete_season", "season_unmonitor_delete_season_delete_show_if_empty", "season_unmonitor_and_unmonitor_show_if_empty", "season_unmonitor_keep_files", "episode_unmonitor_delete_episode", "episode_unmonitor_keep_file"}, Default: "do_nothing"},
		{Name: "rule_id", Type: field.TypeInt},
	}
	// RuleActionStepsTable holds the schema information for the "rule_action_steps" table.
	RuleActionStepsTable = &schema.Table{
		Name:       "rule_action_steps",
		Columns:    RuleActionStepsColumns,
		PrimaryKey: []*schema.Column{RuleActionStepsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rule_action_steps_rules_action_steps",
				Columns:    []*schema.Column{RuleActionStepsColumns[7]},
				RefColumns: []*schema.Column{RulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConnectionsTable,
		LibrariesTable,
		RulesTable,
		RuleActionStepsTable,
	}
)

func init() {
	LibrariesTable.ForeignKeys[0].RefTable = ConnectionsTable
	RulesTable.ForeignKeys[0].RefTable = ConnectionsTable
	RuleActionStepsTable.ForeignKeys[0].RefTable = RulesTable
}
