// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConnectionsColumns holds the columns for the "connections" table.
	ConnectionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"plex", "radarr"}},
		{Name: "name", Type: field.TypeString},
		{Name: "host", Type: field.TypeString},
		{Name: "port", Type: field.TypeInt},
		{Name: "ssl", Type: field.TypeBool, Default: false},
		{Name: "token", Type: field.TypeString},
	}
	// ConnectionsTable holds the schema information for the "connections" table.
	ConnectionsTable = &schema.Table{
		Name:       "connections",
		Columns:    ConnectionsColumns,
		PrimaryKey: []*schema.Column{ConnectionsColumns[0]},
	}
	// LibrariesColumns holds the columns for the "libraries" table.
	LibrariesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "external_id", Type: field.TypeString},
		{Name: "title", Type: field.TypeString},
		{Name: "media_type", Type: field.TypeEnum, Enums: []string{"movie", "show", "artist"}},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "connection_libraries", Type: field.TypeInt},
	}
	// LibrariesTable holds the schema information for the "libraries" table.
	LibrariesTable = &schema.Table{
		Name:       "libraries",
		Columns:    LibrariesColumns,
		PrimaryKey: []*schema.Column{LibrariesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "libraries_connections_libraries",
				Columns:    []*schema.Column{LibrariesColumns[7]},
				RefColumns: []*schema.Column{ConnectionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "library_external_id_connection_libraries",
				Unique:  true,
				Columns: []*schema.Column{LibrariesColumns[3], LibrariesColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConnectionsTable,
		LibrariesTable,
	}
)

func init() {
	LibrariesTable.ForeignKeys[0].RefTable = ConnectionsTable
}
